
ItemSourceDB = {
}
ObjectLocationDB = {
}
CreatureLocationDB = {
}
CreatureDB = {
}
QuestDB = {
}
QuestCompleteDB = {
}
QuestEventDB = {
}
SkillSourceDB = {
}
BigFootBot_Version = {
}
BigFootBot_Info = "cn.logon.warcraftchina.com:凯恩血蹄:zhCN"
PlayersDB = {
	["万俟飞羽:冰风岗"] = {
		["race"] = 4,
		["name"] = "万俟飞羽",
		["guild"] = "属于你的未来",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 12,
		["server"] = "冰风岗",
	},
	["Comprare:影之哀伤"] = {
		["race"] = 4,
		["name"] = "Comprare",
		["guild"] = "Anohana",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 12,
		["server"] = "影之哀伤",
	},
	["一斤毒药:影之哀伤"] = {
		["race"] = 3,
		["name"] = "一斤毒药",
		["guild"] = "HDT",
		["level"] = 1,
		["gender"] = 2,
		["class"] = 5,
		["server"] = "影之哀伤",
	},
	["灬天涯咫尺:奥尔加隆"] = {
		["race"] = 4,
		["name"] = "灬天涯咫尺",
		["guild"] = "Silver Knights",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 6,
		["server"] = "奥尔加隆",
	},
	["雪牧:恶魔之翼"] = {
		["race"] = 4,
		["name"] = "雪牧",
		["guild"] = "Camelot",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 6,
		["server"] = "恶魔之翼",
	},
	["过早:冰风岗"] = {
		["race"] = 4,
		["name"] = "过早",
		["guild"] = "繁盛的小浣熊",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 12,
		["server"] = "冰风岗",
	},
	["风逸墨:冰风岗"] = {
		["race"] = 3,
		["name"] = "风逸墨",
		["guild"] = "为杰沉伦",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 9,
		["server"] = "冰风岗",
	},
	["微笑的雅典娜:影之哀伤"] = {
		["race"] = 4,
		["name"] = "微笑的雅典娜",
		["guild"] = "诗与远方",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 12,
		["server"] = "影之哀伤",
	},
	["带着宝宝走:影之哀伤"] = {
		["race"] = 4,
		["name"] = "带着宝宝走",
		["guild"] = "星光之烁",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 4,
		["server"] = "影之哀伤",
	},
	["法爷在此玩你:冰风岗"] = {
		["race"] = 5,
		["name"] = "法爷在此玩你",
		["guild"] = "大保健会所",
		["level"] = 10,
		["gender"] = 3,
		["class"] = 9,
		["server"] = "冰风岗",
	},
	["夜空最亮的猩:雷霆之王"] = {
		["race"] = 4,
		["name"] = "夜空最亮的猩",
		["guild"] = "春天花花幼稚园",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 12,
		["server"] = "雷霆之王",
	},
	["蒋惊国:冰风岗"] = {
		["race"] = 4,
		["name"] = "蒋惊国",
		["guild"] = "老閪",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 11,
		["server"] = "冰风岗",
	},
	["幻影丶:索瑞森"] = {
		["race"] = 2,
		["name"] = "幻影丶",
		["guild"] = "污妖王",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 8,
		["server"] = "索瑞森",
	},
	["若凛:凯恩血蹄"] = {
		["race"] = 4,
		["name"] = "若凛",
		["guild"] = "Dark Hours",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 12,
		["server"] = "凯恩血蹄",
	},
	["为战三三:雷霆之王"] = {
		["race"] = 5,
		["name"] = "为战三三",
		["guild"] = "为战",
		["level"] = 1,
		["gender"] = 3,
		["class"] = 2,
		["server"] = "雷霆之王",
	},
	["影伤为战:影之哀伤"] = {
		["race"] = 5,
		["name"] = "影伤为战",
		["guild"] = "为战",
		["level"] = 1,
		["gender"] = 3,
		["class"] = 2,
		["server"] = "影之哀伤",
	},
	["莱桀:黑暗魅影"] = {
		["race"] = 4,
		["name"] = "莱桀",
		["guild"] = "梦星辰",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 7,
		["server"] = "黑暗魅影",
	},
	["起不了名啊:影之哀伤"] = {
		["race"] = 5,
		["name"] = "起不了名啊",
		["guild"] = "永不凋零",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 7,
		["server"] = "影之哀伤",
	},
	["高姿态美屡:冰风岗"] = {
		["race"] = 4,
		["name"] = "高姿态美屡",
		["guild"] = "灵魂共鸣",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 9,
		["server"] = "冰风岗",
	},
	["卧到有埋伏:卡德加"] = {
		["race"] = 4,
		["name"] = "卧到有埋伏",
		["guild"] = "自由信仰",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 12,
		["server"] = "卡德加",
	},
	["Picca:奥尔加隆"] = {
		["race"] = 14,
		["name"] = "Picca",
		["guild"] = "Night dynasty",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 8,
		["server"] = "奥尔加隆",
	},
	["小胡啊:通灵学院"] = {
		["race"] = 14,
		["name"] = "小胡啊",
		["guild"] = "For The Vow",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 6,
		["server"] = "通灵学院",
	},
	["Raligun:通灵学院"] = {
		["race"] = 4,
		["name"] = "Raligun",
		["guild"] = "緣來一家人",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 2,
		["server"] = "通灵学院",
	},
	["曹小树:符文图腾"] = {
		["race"] = 4,
		["name"] = "曹小树",
		["guild"] = "梦星辰",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 12,
		["server"] = "符文图腾",
	},
	["萌萌的骑士:冰风岗"] = {
		["race"] = 4,
		["name"] = "萌萌的骑士",
		["guild"] = "圣战的終焉",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 3,
		["server"] = "冰风岗",
	},
	["新人夂探路者:冰风岗"] = {
		["race"] = 1,
		["name"] = "新人夂探路者",
		["guild"] = "後起之秀",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 2,
		["server"] = "冰风岗",
	},
	["Xmxi:冰风岗"] = {
		["race"] = 3,
		["name"] = "Xmxi",
		["guild"] = "龙 凶",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 9,
		["server"] = "冰风岗",
	},
	["忘记世界:加里索斯"] = {
		["race"] = 3,
		["name"] = "忘记世界",
		["guild"] = "啴裑貴蔟",
		["level"] = 91,
		["gender"] = 2,
		["class"] = 7,
		["server"] = "加里索斯",
	},
	["Presbytes:恶魔之翼"] = {
		["race"] = 2,
		["name"] = "Presbytes",
		["guild"] = "通灵学院 无敌工会",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 3,
		["server"] = "恶魔之翼",
	},
	["霊娜:黑暗魅影"] = {
		["race"] = 4,
		["name"] = "霊娜",
		["guild"] = "永远的部落",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 4,
		["server"] = "黑暗魅影",
	},
	["魔王丶大大:影之哀伤"] = {
		["race"] = 4,
		["name"] = "魔王丶大大",
		["guild"] = "天欲",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 12,
		["server"] = "影之哀伤",
	},
	["微灬笑:卡德加"] = {
		["race"] = 4,
		["name"] = "微灬笑",
		["guild"] = "Trouble Maker",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 6,
		["server"] = "卡德加",
	},
	["剣舞滄穹:奥尔加隆"] = {
		["race"] = 4,
		["name"] = "剣舞滄穹",
		["guild"] = "致青春之荣耀归来",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 12,
		["server"] = "奥尔加隆",
	},
	["琉璃色的寂寞:雷霆之王"] = {
		["race"] = 4,
		["name"] = "琉璃色的寂寞",
		["guild"] = "秋叶",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 9,
		["server"] = "雷霆之王",
	},
	["爆破专家:影之哀伤"] = {
		["race"] = 4,
		["name"] = "爆破专家",
		["guild"] = "大灾变",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 3,
		["server"] = "影之哀伤",
	},
	["冷嘲丶:影之哀伤"] = {
		["race"] = 2,
		["name"] = "冷嘲丶",
		["guild"] = "Stars Shine",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 10,
		["server"] = "影之哀伤",
	},
	["太君:影之哀伤"] = {
		["race"] = 4,
		["name"] = "太君",
		["guild"] = "北斗望京华",
		["level"] = 44,
		["gender"] = 3,
		["class"] = 3,
		["server"] = "影之哀伤",
	},
	["Beetch:冰风岗"] = {
		["race"] = 4,
		["name"] = "Beetch",
		["guild"] = "Merry",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 4,
		["server"] = "冰风岗",
	},
	["可以丶很炫酷:影之哀伤"] = {
		["race"] = 3,
		["name"] = "可以丶很炫酷",
		["guild"] = "诗与远方",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 1,
		["server"] = "影之哀伤",
	},
	["Magelily:奥尔加隆"] = {
		["race"] = 4,
		["name"] = "Magelily",
		["guild"] = "炮灰集中营",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 3,
		["server"] = "奥尔加隆",
	},
	["永远罘离卜弃:雷霆之王"] = {
		["race"] = 4,
		["name"] = "永远罘离卜弃",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 5,
		["server"] = "雷霆之王",
	},
	["樱花落:影之哀伤"] = {
		["race"] = 4,
		["name"] = "樱花落",
		["guild"] = "刘宅村",
		["level"] = 93,
		["gender"] = 3,
		["class"] = 5,
		["server"] = "影之哀伤",
	},
	["九为战九:雷霆之王"] = {
		["race"] = 5,
		["name"] = "九为战九",
		["guild"] = "为战",
		["level"] = 1,
		["gender"] = 3,
		["class"] = 4,
		["server"] = "雷霆之王",
	},
	["光耀圣盾:黑暗魅影"] = {
		["race"] = 4,
		["name"] = "光耀圣盾",
		["guild"] = "复仇纹章",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 3,
		["server"] = "黑暗魅影",
	},
	["心雨滴:试炼之环"] = {
		["race"] = 4,
		["name"] = "心雨滴",
		["guild"] = "十八岁请给我个姑娘",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 9,
		["server"] = "试炼之环",
	},
	["冰结紫原:影之哀伤"] = {
		["race"] = 2,
		["name"] = "冰结紫原",
		["guild"] = "紫菀之夜",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 10,
		["server"] = "影之哀伤",
	},
	["圣曲:索瑞森"] = {
		["race"] = 4,
		["name"] = "圣曲",
		["guild"] = "Vortex",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 3,
		["server"] = "索瑞森",
	},
	["为战冰风:冰风岗"] = {
		["race"] = 5,
		["name"] = "为战冰风",
		["guild"] = "为战",
		["level"] = 1,
		["gender"] = 3,
		["class"] = 2,
		["server"] = "冰风岗",
	},
	["风筝猎杀:冰风岗"] = {
		["race"] = 5,
		["name"] = "风筝猎杀",
		["level"] = 68,
		["gender"] = 3,
		["class"] = 4,
		["server"] = "冰风岗",
	},
	["納蘭曉狐狸:影之哀伤"] = {
		["race"] = 4,
		["name"] = "納蘭曉狐狸",
		["guild"] = "云帝",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 7,
		["server"] = "影之哀伤",
	},
	["毁灭光明:影之哀伤"] = {
		["race"] = 4,
		["name"] = "毁灭光明",
		["guild"] = "刘宅村",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 1,
		["server"] = "影之哀伤",
	},
	["马尾辫灬姑娘:奥尔加隆"] = {
		["race"] = 14,
		["name"] = "马尾辫灬姑娘",
		["guild"] = "缘丶夕",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 8,
		["server"] = "奥尔加隆",
	},
	["风一般的女纸:雷霆之王"] = {
		["race"] = 4,
		["name"] = "风一般的女纸",
		["guild"] = "放牛班的春天",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 12,
		["server"] = "雷霆之王",
	},
	["丶月未央:影之哀伤"] = {
		["race"] = 4,
		["name"] = "丶月未央",
		["guild"] = "NightmareTeam",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 9,
		["server"] = "影之哀伤",
	},
	["知足长乐:冰风岗"] = {
		["race"] = 4,
		["name"] = "知足长乐",
		["guild"] = "梦境之地",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 3,
		["server"] = "冰风岗",
	},
	["黑皮牛二:熊猫酒仙"] = {
		["race"] = 2,
		["name"] = "黑皮牛二",
		["guild"] = "飘 渺",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 3,
		["server"] = "熊猫酒仙",
	},
	["風暴丶烈酒:影之哀伤"] = {
		["race"] = 3,
		["name"] = "風暴丶烈酒",
		["guild"] = "墮天之翼",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 1,
		["server"] = "影之哀伤",
	},
	["乱舞刃:冰风岗"] = {
		["race"] = 4,
		["name"] = "乱舞刃",
		["guild"] = "那些年我们一起睡过的女孩",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 12,
		["server"] = "冰风岗",
	},
	["子溪:冰风岗"] = {
		["race"] = 4,
		["name"] = "子溪",
		["guild"] = "玲瓏小筑",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 4,
		["server"] = "冰风岗",
	},
	["Blacksola:奥尔加隆"] = {
		["race"] = 1,
		["name"] = "Blacksola",
		["guild"] = "逐光",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 4,
		["server"] = "奥尔加隆",
	},
	["菲丽丝:影之哀伤"] = {
		["race"] = 4,
		["name"] = "菲丽丝",
		["guild"] = "聖鬥士",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 3,
		["server"] = "影之哀伤",
	},
	["围覌不怕事大:卡德加"] = {
		["race"] = 4,
		["name"] = "围覌不怕事大",
		["guild"] = "太污了",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 12,
		["server"] = "卡德加",
	},
	["小查:奥尔加隆"] = {
		["race"] = 5,
		["name"] = "小查",
		["guild"] = "Hero",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 4,
		["server"] = "奥尔加隆",
	},
	["魔灵猎魄:影之哀伤"] = {
		["race"] = 5,
		["name"] = "魔灵猎魄",
		["guild"] = "灵魂征战",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 4,
		["server"] = "影之哀伤",
	},
	["丶失眠梦:雷霆之王"] = {
		["race"] = 5,
		["name"] = "丶失眠梦",
		["guild"] = "傲翼苍穹",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 4,
		["server"] = "雷霆之王",
	},
	["银殇:冰风岗"] = {
		["race"] = 4,
		["name"] = "银殇",
		["guild"] = "漫花飞舞",
		["level"] = 110,
		["gender"] = 3,
		["class"] = 3,
		["server"] = "冰风岗",
	},
	["寻找高中女生:试炼之环"] = {
		["race"] = 3,
		["name"] = "寻找高中女生",
		["guild"] = "战歌",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 5,
		["server"] = "试炼之环",
	},
	["神意灬七爷:熵魔"] = {
		["race"] = 1,
		["name"] = "神意灬七爷",
		["guild"] = "亍伤的童话",
		["level"] = 110,
		["gender"] = 2,
		["class"] = 8,
		["server"] = "熵魔",
	},
}
UtilDB = {
	["M"] = {
		["NumSysUnread"] = 0,
		["MD5"] = "14540011732267283577243464264215685923",
		["NumNormalRead"] = 2,
		["NumSysRead"] = 0,
		["NumNormalUnread"] = 0,
	},
}
NPCMarkCollectionDB = {
}
BigFootBot_collectData = {
	["CombatBattlePetData"] = {
		["森林蛾"] = {
			["PetType"] = 3,
			["enemyPetType"] = 1,
			["StyPetType"] = "飞行",
			["health"] = 1073,
			["name"] = "森林蛾",
			["speciesName"] = "森林蛾",
			["speed"] = 317,
			["level"] = 22,
			["maxHealth"] = 1073,
			["attack"] = 224,
		},
		["超能浣熊"] = {
			["PetType"] = 5,
			["enemyPetType"] = 7,
			["StyPetType"] = "小动物",
			["name"] = "超能浣熊",
			["health"] = 1000,
			["speed"] = 275,
			["speciesName"] = "超能浣熊",
			["level"] = 25,
			["maxHealth"] = 1000,
			["attack"] = 176,
		},
		["长钉"] = {
			["PetType"] = 8,
			["enemyPetType"] = 1,
			["StyPetType"] = "野兽",
			["health"] = 194,
			["name"] = "长钉",
			["speciesName"] = "长钉",
			["speed"] = 19,
			["level"] = 2,
			["maxHealth"] = 194,
			["attack"] = 19,
		},
		["骨刺蜥蜴"] = {
			["PetType"] = 8,
			["enemyPetType"] = 7,
			["StyPetType"] = "野兽",
			["name"] = "骨刺蜥蜴",
			["health"] = 118,
			["speed"] = 12,
			["speciesName"] = "骨刺蜥蜴",
			["level"] = 1,
			["maxHealth"] = 118,
			["attack"] = 9,
		},
		["丝翅蛾"] = {
			["PetType"] = 3,
			["enemyPetType"] = 1,
			["StyPetType"] = "飞行",
			["health"] = 890,
			["name"] = "丝翅蛾",
			["speciesName"] = "丝翅蛾",
			["speed"] = 345,
			["level"] = 22,
			["maxHealth"] = 890,
			["attack"] = 194,
		},
		["恐惧爬行者"] = {
			["PetType"] = 5,
			["enemyPetType"] = 1,
			["StyPetType"] = "小动物",
			["health"] = 118,
			["name"] = "恐惧爬行者",
			["speciesName"] = "恐惧爬行者",
			["speed"] = 9,
			["level"] = 1,
			["maxHealth"] = 118,
			["attack"] = 9,
		},
		["棘爪巢蛛"] = {
			["PetType"] = 8,
			["enemyPetType"] = 7,
			["StyPetType"] = "野兽",
			["name"] = "棘爪巢蛛",
			["health"] = 1070,
			["speed"] = 255,
			["speciesName"] = "棘爪巢蛛",
			["level"] = 25,
			["maxHealth"] = 1070,
			["attack"] = 226,
		},
		["蜣螂"] = {
			["PetType"] = 5,
			["enemyPetType"] = 7,
			["StyPetType"] = "小动物",
			["name"] = "蜣螂",
			["health"] = 122,
			["speed"] = 9,
			["speciesName"] = "蜣螂",
			["level"] = 1,
			["maxHealth"] = 122,
			["attack"] = 10,
		},
		["海岸沙鸥"] = {
			["PetType"] = 3,
			["enemyPetType"] = 7,
			["StyPetType"] = "飞行",
			["name"] = "海岸沙鸥",
			["health"] = 1000,
			["speed"] = 413,
			["speciesName"] = "海岸沙鸥",
			["level"] = 25,
			["maxHealth"] = 1000,
			["attack"] = 176,
		},
		["黑色王蛇"] = {
			["PetType"] = 8,
			["enemyPetType"] = 1,
			["StyPetType"] = "野兽",
			["health"] = 325,
			["name"] = "黑色王蛇",
			["speciesName"] = "黑色王蛇",
			["speed"] = 60,
			["level"] = 5,
			["maxHealth"] = 325,
			["attack"] = 51,
		},
		["克洛玛尼斯"] = {
			["PetType"] = 2,
			["enemyPetType"] = 7,
			["StyPetType"] = "龙类",
			["name"] = "克洛玛尼斯",
			["health"] = 470,
			["speed"] = 62,
			["speciesName"] = "克洛玛尼斯",
			["level"] = 6,
			["maxHealth"] = 470,
			["attack"] = 66,
		},
		["小野兔"] = {
			["PetType"] = 5,
			["enemyPetType"] = 1,
			["StyPetType"] = "小动物",
			["health"] = 940,
			["name"] = "小野兔",
			["speciesName"] = "小野兔",
			["speed"] = 242,
			["level"] = 22,
			["maxHealth"] = 940,
			["attack"] = 169,
		},
		["迪娜"] = {
			["PetType"] = 9,
			["enemyPetType"] = 7,
			["StyPetType"] = "水栖",
			["name"] = "迪娜",
			["health"] = 1627,
			["speed"] = 289,
			["speciesName"] = "迪娜",
			["level"] = 25,
			["maxHealth"] = 1627,
			["attack"] = 273,
		},
		["雷米"] = {
			["PetType"] = 5,
			["enemyPetType"] = 7,
			["StyPetType"] = "小动物",
			["name"] = "雷米",
			["health"] = 1481,
			["speed"] = 325,
			["speciesName"] = "雷米",
			["level"] = 25,
			["maxHealth"] = 1481,
			["attack"] = 276,
		},
		["古斯特"] = {
			["PetType"] = 10,
			["enemyPetType"] = 7,
			["StyPetType"] = "机械",
			["name"] = "古斯特",
			["health"] = 1546,
			["speed"] = 305,
			["speciesName"] = "古斯特",
			["level"] = 25,
			["maxHealth"] = 1546,
			["attack"] = 273,
		},
		["喷毒幼蛛"] = {
			["PetType"] = 8,
			["enemyPetType"] = 7,
			["StyPetType"] = "野兽",
			["name"] = "喷毒幼蛛",
			["health"] = 370,
			["speed"] = 65,
			["speciesName"] = "喷毒幼蛛",
			["level"] = 6,
			["maxHealth"] = 370,
			["attack"] = 65,
		},
		["机械小鸡"] = {
			["PetType"] = 10,
			["enemyPetType"] = 1,
			["StyPetType"] = "机械",
			["health"] = 168,
			["name"] = "机械小鸡",
			["speciesName"] = "机械小鸡",
			["speed"] = 10,
			["level"] = 1,
			["maxHealth"] = 168,
			["attack"] = 10,
		},
		["姆塔"] = {
			["PetType"] = 5,
			["enemyPetType"] = 1,
			["StyPetType"] = "小动物",
			["health"] = 194,
			["name"] = "姆塔",
			["speciesName"] = "姆塔",
			["speed"] = 19,
			["level"] = 2,
			["maxHealth"] = 194,
			["attack"] = 19,
		},
		["雪豹幼崽"] = {
			["PetType"] = 8,
			["enemyPetType"] = 7,
			["StyPetType"] = "野兽",
			["health"] = 123,
			["name"] = "雪豹幼崽",
			["speciesName"] = "雪豹幼崽",
			["speed"] = 10,
			["level"] = 1,
			["maxHealth"] = 123,
			["attack"] = 12,
		},
		["布洛提斯"] = {
			["PetType"] = 9,
			["enemyPetType"] = 7,
			["StyPetType"] = "水栖",
			["health"] = 2999,
			["name"] = "布洛提斯",
			["speciesName"] = "布洛提斯",
			["speed"] = 280,
			["level"] = 25,
			["maxHealth"] = 2999,
			["attack"] = 252,
		},
		["锈色蜗牛"] = {
			["PetType"] = 5,
			["enemyPetType"] = 7,
			["StyPetType"] = "小动物",
			["name"] = "锈色蜗牛",
			["health"] = 438,
			["speed"] = 42,
			["speciesName"] = "锈色蜗牛",
			["level"] = 5,
			["maxHealth"] = 438,
			["attack"] = 58,
		},
	},
	["BigFootBank_Data"] = {
		["Items"] = {
			["无主的黑市宝箱"] = {
				["texture"] = "Interface\\Icons\\INV_MISC_LOCKBOX_1",
				["itemType"] = "垃圾",
				["link"] = "|cffa335ee|Hitem:102137:0:0:0:0:0:0:0:90:0:0|h[无主的黑市宝箱]|h|r",
				["sellerName"] = "郭雅夫人",
				["currBid"] = 210000000,
				["usable"] = 1,
				["minIncrement"] = 10000000,
				["minBid"] = 220000000,
				["quantity"] = 1,
				["name"] = "无主的黑市宝箱",
				["numBids"] = 3,
				["marketID"] = 67,
				["level"] = 1,
				["timeLeft"] = 3,
				["levelType"] = "REQ_LEVEL_ABBR",
			},
			["浸血的邀请函"] = {
				["texture"] = "Interface\\Icons\\INV_MISC_BANDAGE_05",
				["itemType"] = "任务",
				["link"] = "|cff0070dd|Hitem:93194:0:0:0:0:0:0:0:90:0:0|h[浸血的邀请函]|h|r",
				["sellerName"] = "郭雅夫人",
				["currBid"] = 0,
				["usable"] = 1,
				["minIncrement"] = 1,
				["minBid"] = 10000000,
				["quantity"] = 1,
				["name"] = "浸血的邀请函",
				["numBids"] = 0,
				["marketID"] = 45,
				["level"] = 90,
				["timeLeft"] = 3,
				["levelType"] = "REQ_LEVEL_ABBR",
			},
		},
		["server"] = "凯恩血蹄",
		["time"] = "2014-7-31-18-16",
		["numItems"] = 3,
	},
	["WildBattlePetData"] = {
		["0xF130F2A40013C172"] = {
			["Map"] = "杜隆塔尔",
			["X"] = 45,
			["Name"] = "恐惧爬行者",
			["TypeId"] = 5,
			["MapLevel"] = 0,
			["Level"] = 1,
			["MapZone"] = "杜隆塔尔",
			["Y"] = 30,
		},
		["0xF5311F460007FD1C"] = {
			["Map"] = "永恒岛",
			["X"] = 42,
			["Name"] = "灰翼蛾",
			["TypeId"] = 3,
			["MapLevel"] = 0,
			["Level"] = 25,
			["MapZone"] = "永恒岛",
			["Y"] = 66,
		},
		["0xF5311F46000DACB8"] = {
			["Map"] = "永恒岛",
			["X"] = 51,
			["Name"] = "灰翼蛾",
			["TypeId"] = 3,
			["MapLevel"] = 0,
			["Level"] = 25,
			["MapZone"] = "永恒岛",
			["Y"] = 68,
		},
		["0xF130F2A200140600"] = {
			["Map"] = "奥格瑞玛",
			["X"] = 50,
			["Name"] = "骨刺蜥蜴",
			["TypeId"] = 8,
			["MapLevel"] = 1,
			["Level"] = 1,
			["MapZone"] = "力量谷",
			["Y"] = 83,
		},
		["0xF130F6540000261C"] = {
			["Map"] = "四风谷",
			["X"] = 58,
			["Name"] = "软壳幼龟",
			["Y"] = 35,
			["MapLevel"] = 0,
			["Level"] = 24,
			["MapZone"] = "金扇泽",
			["TypeId"] = 9,
		},
		["0xF530EFB6000EBFC5"] = {
			["Map"] = "永恒岛",
			["X"] = 38,
			["Name"] = "老鼠",
			["TypeId"] = 5,
			["MapLevel"] = 0,
			["Level"] = 25,
			["MapZone"] = "天神庭院",
			["Y"] = 47,
		},
		["0xF530F67800008A15"] = {
			["Map"] = "四风谷",
			["X"] = 67,
			["Name"] = "泽地小歌手",
			["Y"] = 48,
			["MapLevel"] = 0,
			["Level"] = 23,
			["MapZone"] = "四风谷",
			["TypeId"] = 5,
		},
		["Creature-0-3126-1220-17652-61327-000041D0BF"] = {
			["Name"] = "蜘蛛",
			["Level"] = 25,
			["MapLevel"] = 0,
			["TypeId"] = 8,
		},
		["0xF130F2A2001407D5"] = {
			["Map"] = "奥格瑞玛",
			["X"] = 53,
			["Name"] = "骨刺蜥蜴",
			["TypeId"] = 8,
			["MapLevel"] = 1,
			["Level"] = 1,
			["MapZone"] = "力量谷",
			["Y"] = 77,
		},
		["0xF130F2A20006C94D"] = {
			["Map"] = "奥格瑞玛",
			["X"] = 44,
			["Name"] = "骨刺蜥蜴",
			["Y"] = 70,
			["MapLevel"] = 1,
			["Level"] = 1,
			["MapZone"] = "力量谷",
			["TypeId"] = 8,
		},
		["0xF130F2A30033BF9B"] = {
			["Map"] = "奥格瑞玛",
			["X"] = 50,
			["Name"] = "蜣螂",
			["Y"] = 78,
			["MapLevel"] = 1,
			["Level"] = 1,
			["MapZone"] = "力量谷",
			["TypeId"] = 5,
		},
		["0xF530EFB60008D993"] = {
			["Map"] = "永恒岛",
			["X"] = 38,
			["Name"] = "老鼠",
			["TypeId"] = 5,
			["MapLevel"] = 0,
			["Level"] = 25,
			["MapZone"] = "天神庭院",
			["Y"] = 47,
		},
		["0xF130F0F9000CF740"] = {
			["Map"] = "新工匠镇",
			["X"] = 42,
			["Name"] = "雪豹幼崽",
			["TypeId"] = 8,
			["MapLevel"] = 0,
			["Level"] = 1,
			["MapZone"] = "新工匠镇",
			["Y"] = 36,
		},
		["Creature-0-3910-530-67-61385-00005F4273"] = {
			["Name"] = "燃灰蝰蛇",
			["Level"] = 20,
			["MapLevel"] = 0,
			["TypeId"] = 8,
		},
		["0xF530F2E2001BAF6C"] = {
			["Map"] = "海加尔山",
			["X"] = 39,
			["Name"] = "小野兔",
			["Y"] = 41,
			["MapLevel"] = 0,
			["Level"] = 23,
			["MapZone"] = "世界之脊",
			["TypeId"] = 5,
		},
		["0xF130F67800008609"] = {
			["Map"] = "四风谷",
			["X"] = 67,
			["Name"] = "泽地小歌手",
			["Y"] = 48,
			["MapLevel"] = 0,
			["Level"] = 24,
			["MapZone"] = "四风谷",
			["TypeId"] = 5,
		},
		["Creature-0-3910-1220-17954-110741-00006E23F4"] = {
			["MapLevel"] = 0,
			["Level"] = 25,
			["TypeId"] = 5,
			["Name"] = "闪蹄小鹿",
		},
		["Creature-0-3126-1220-16958-97559-0000665FE5"] = {
			["MapLevel"] = 0,
			["Level"] = 25,
			["TypeId"] = 9,
			["Name"] = "泉眼水黾",
		},
		["0xF130F2A3001404D0"] = {
			["Map"] = "奥格瑞玛",
			["X"] = 55,
			["Name"] = "蜣螂",
			["TypeId"] = 5,
			["MapLevel"] = 1,
			["Level"] = 1,
			["MapZone"] = "力量谷",
			["Y"] = 84,
		},
		["Creature-0-3116-1220-10925-97741-0000480089"] = {
			["MapLevel"] = 0,
			["Level"] = 25,
			["TypeId"] = 8,
			["Name"] = "黑脚狐幼崽",
		},
		["0xF130F2A20006A498"] = {
			["Map"] = "奥格瑞玛",
			["X"] = 54,
			["Name"] = "骨刺蜥蜴",
			["Y"] = 84,
			["MapLevel"] = 1,
			["Level"] = 1,
			["MapZone"] = "力量谷",
			["TypeId"] = 8,
		},
		["0xF130F9D5000016C2"] = {
			["Map"] = "螳螂高原",
			["X"] = 78,
			["Name"] = "牦鼠",
			["TypeId"] = 5,
			["MapLevel"] = 0,
			["Level"] = 24,
			["MapZone"] = "润泥藏身处",
			["Y"] = 79,
		},
		["Creature-0-3121-1220-246-97840-000016BBE9"] = {
			["Name"] = "紫红泰斑蛇",
			["Level"] = 25,
			["MapLevel"] = 0,
			["TypeId"] = 8,
		},
		["Creature-0-3039-1220-27677-105898-00004B37BE"] = {
			["MapLevel"] = 0,
			["Level"] = 25,
			["TypeId"] = 9,
			["Name"] = "布洛提斯",
		},
		["0xF130F6780069A35A"] = {
			["Map"] = "四风谷",
			["X"] = 34,
			["Name"] = "泽地小歌手",
			["Y"] = 44,
			["MapLevel"] = 0,
			["Level"] = 23,
			["MapZone"] = "汇风岭",
			["TypeId"] = 5,
		},
		["Creature-0-3905-1220-1097-63062-0001650900"] = {
			["MapLevel"] = 0,
			["Level"] = 25,
			["TypeId"] = 5,
			["Name"] = "超能浣熊",
		},
		["Creature-0-3904-1-25938-62116-0001CC25BD"] = {
			["MapLevel"] = 0,
			["Level"] = 1,
			["TypeId"] = 5,
			["Name"] = "恐惧爬行者",
		},
		["0xF1310CE60030603D"] = {
			["Map"] = "新工匠镇",
			["X"] = 40,
			["Name"] = "焊接小猫",
			["Y"] = 48,
			["MapLevel"] = 0,
			["Level"] = 1,
			["MapZone"] = "剧毒机场",
			["TypeId"] = 10,
		},
		["0xF530F651000F0BBC"] = {
			["Map"] = "四风谷",
			["X"] = 50,
			["Name"] = "四方水獭",
			["Y"] = 27,
			["MapLevel"] = 0,
			["Level"] = 23,
			["MapZone"] = "汇风岭",
			["TypeId"] = 9,
		},
		["0xF130F61C000060C5"] = {
			["Map"] = "翡翠林",
			["X"] = 38,
			["Name"] = "林地毒蛇",
			["TypeId"] = 8,
			["MapLevel"] = 0,
			["Level"] = 23,
			["MapZone"] = "翠林之心",
			["Y"] = 49,
		},
		["Creature-0-3126-1220-17652-97840-0000450B2B"] = {
			["MapLevel"] = 0,
			["Level"] = 25,
			["TypeId"] = 8,
			["Name"] = "紫红泰斑蛇",
		},
		["0xF5311F460004F644"] = {
			["Map"] = "永恒岛",
			["X"] = 43,
			["Name"] = "灰翼蛾",
			["TypeId"] = 3,
			["MapLevel"] = 0,
			["Level"] = 25,
			["MapZone"] = "永恒岛",
			["Y"] = 72,
		},
		["Creature-0-3905-1220-1097-99528-00006607EF"] = {
			["Name"] = "棘爪巢蛛",
			["Level"] = 25,
			["MapLevel"] = 0,
			["TypeId"] = 8,
		},
		["0xF130F3A5001AFC6B"] = {
			["Map"] = "海加尔山",
			["X"] = 64,
			["Name"] = "丝翅蛾",
			["TypeId"] = 3,
			["MapLevel"] = 0,
			["Level"] = 22,
			["MapZone"] = "诺达希尔",
			["Y"] = 24,
		},
		["0xF130F83B00003BD6"] = {
			["Map"] = "昆莱山",
			["X"] = 63,
			["Name"] = "平原监视者",
			["TypeId"] = 8,
			["MapLevel"] = 0,
			["Level"] = 24,
			["MapZone"] = "野牛人前线",
			["Y"] = 71,
		},
		["0xF130F651000029E6"] = {
			["Map"] = "四风谷",
			["X"] = 82,
			["Name"] = "四方水獭",
			["Y"] = 39,
			["MapLevel"] = 0,
			["Level"] = 25,
			["MapZone"] = "炎子江",
			["TypeId"] = 9,
		},
		["0xF130F2A30005CCBC"] = {
			["Map"] = "奥格瑞玛",
			["X"] = 47,
			["Name"] = "蜣螂",
			["Y"] = 74,
			["MapLevel"] = 1,
			["Level"] = 1,
			["MapZone"] = "力量谷",
			["TypeId"] = 5,
		},
		["0xF130F2A20006A439"] = {
			["Map"] = "奥格瑞玛",
			["X"] = 46,
			["Name"] = "骨刺蜥蜴",
			["Y"] = 79,
			["MapLevel"] = 1,
			["Level"] = 1,
			["MapZone"] = "力量谷",
			["TypeId"] = 8,
		},
		["0xF530F61C002038B0"] = {
			["Map"] = "翡翠林",
			["X"] = 27,
			["Name"] = "林地毒蛇",
			["TypeId"] = 8,
			["MapLevel"] = 0,
			["Level"] = 23,
			["MapZone"] = "努卡努卡营地",
			["Y"] = 37,
		},
		["0xF130F2A3001116AD"] = {
			["Map"] = "奥格瑞玛",
			["X"] = 48,
			["Name"] = "蜣螂",
			["TypeId"] = 5,
			["MapLevel"] = 1,
			["Level"] = 1,
			["MapZone"] = "力量谷",
			["Y"] = 76,
		},
		["0xF5311F46000FA2EC"] = {
			["Map"] = "永恒岛",
			["X"] = 56,
			["Name"] = "灰翼蛾",
			["TypeId"] = 3,
			["MapLevel"] = 0,
			["Level"] = 25,
			["MapZone"] = "红石谷",
			["Y"] = 55,
		},
		["Creature-0-3116-1220-10925-98192-00004696FC"] = {
			["TypeId"] = 3,
			["Level"] = 25,
			["Name"] = "猪鼻蝙蝠",
			["MapLevel"] = 0,
		},
		["0xF130F2A30014076E"] = {
			["Map"] = "奥格瑞玛",
			["X"] = 48,
			["Name"] = "蜣螂",
			["TypeId"] = 5,
			["MapLevel"] = 1,
			["Level"] = 1,
			["MapZone"] = "力量谷",
			["Y"] = 76,
		},
		["Creature-0-3121-1220-7221-97511-000048488E"] = {
			["MapLevel"] = 0,
			["Level"] = 25,
			["TypeId"] = 3,
			["Name"] = "荧光水蝇",
		},
		["0xF130F2A300141CB6"] = {
			["Map"] = "奥格瑞玛",
			["X"] = 50,
			["Name"] = "蜣螂",
			["TypeId"] = 5,
			["MapLevel"] = 1,
			["Level"] = 1,
			["MapZone"] = "力量谷",
			["Y"] = 78,
		},
		["Creature-0-3121-1-30034-62114-0000087E01"] = {
			["MapLevel"] = 2,
			["Level"] = 1,
			["TypeId"] = 8,
			["Name"] = "骨刺蜥蜴",
		},
	},
}
SpamChatDB = {
	["factionGroup"] = "Horde",
	[1489656038] = {
		["name"] = "箜之轨迹-凯恩血蹄",
		["content"] = " |cffa335ee|Hitem:138019::::::::110:251:8257536:::1501:11:6:4:10:1:::|h[史诗钥石]|h|r",
	},
	[1489658037] = {
		["name"] = "魔丨瞳-卡德加",
		["content"] = "@XjFeU0NMQ15OMl5OMTkzNF5e",
	},
	[1489658340] = {
		["name"] = "你很棒棒-冰风岗",
		["content"] = "{心}《 童话• 》•H•{rt3}(暗#也){rt3}快，好，气氛和谐，欢迎来购，让你更强，",
	},
	[1489657070] = {
		["name"] = "Aryasta-卡德加",
		["content"] = "@XjFeU0NMQ15OMV5OMjMwOTg3Xl4",
	},
	[1489657389] = {
		["name"] = "你很棒棒-冰风岗",
		["content"] = "{心}《 童话• 》•H•{rt3}(暗#也){rt3}快，好，气氛和谐，欢迎来购，让你更强，",
	},
	[1489658641] = {
		["name"] = "你很棒棒-冰风岗",
		["content"] = "{心}《 童话• 》•H•{rt3}(暗#也){rt3}快，好，气氛和谐，欢迎来购，让你更强，",
	},
	[1489658942] = {
		["name"] = "你很棒棒-冰风岗",
		["content"] = "{心}《 童话• 》•H•{rt3}(暗#也){rt3}快，好，气氛和谐，欢迎来购，让你更强，",
	},
	[1489656655] = {
		["name"] = "暗夜来消廢",
		["content"] = " {rt4}<H-‘要-’塞>{rt4}  ⒈-⒑—— 趟;'着;'成;'强;'者",
	},
	[1489657704] = {
		["name"] = "好酷錒-卡德加",
		["content"] = "有公会收人么",
	},
	[1489656354] = {
		["name"] = "哦丶我死了-卡德加",
		["content"] = "新人求个和谐工会",
	},
	[1489655707] = {
		["name"] = "迷之自信",
		["content"] = "凯恩【有缘】10年老会为开荒M夜店补充各稳定职业.活动时间451晚8.00-11.00.工会气氛和谐.轻松愉快.每周稳定伐木H+M前3.有意M谈.我们只要快乐  不追求进度 扰屏请见谅!",
	},
	["realm"] = "凯恩血蹄",
}
