
DBMWorldEvents_AllSavedVars = {
	["若凛-凯恩血蹄"] = {
		["d288"] = {
			{
				["Enabled"] = true,
				["TrioActiveTimer"] = true,
				["HealthFrame"] = false,
				["Timer68821castTColor"] = 0,
				["announce68821cast"] = true,
				["SpecWarn68927moveSWSound"] = 1,
				["SpecWarn68927move"] = true,
				["SpecWarn68934moveSWSound"] = 1,
				["SpecWarn68927moveSWNote"] = true,
				["Timer68821cast"] = true,
				["SpecWarn68934move"] = true,
				["SpecWarn68934moveSWNote"] = true,
				["TrioActiveTimerTColor"] = 0,
			}, -- [1]
		},
		["d286"] = {
			{
				["Enabled"] = true,
				["specWarnAttack"] = true,
				["HealthFrame"] = false,
				["specWarnAttackSWNote"] = true,
				["Emerged"] = true,
				["SubmergTimerTColor"] = 6,
				["SubmergTimer"] = true,
				["specWarnAttackSWSound"] = 1,
				["announce37751spell"] = true,
				["EmergeTimer"] = true,
				["EmergeTimerTColor"] = 6,
			}, -- [1]
		},
		["d287"] = {
			{
				["announceother51413target"] = true,
				["Timer47340target"] = false,
				["Timer51413target"] = true,
				["HealthFrame"] = false,
				["specWarnBrew"] = true,
				["specWarnBrewStun"] = true,
				["specWarnBrewStunSWNote"] = true,
				["Timer47310cast"] = true,
				["specWarnBrewStunSWSound"] = 1,
				["Timer47376targetTColor"] = 0,
				["Timer51413targetTColor"] = 0,
				["Timer47376target"] = false,
				["specWarnBrewSWSound"] = 1,
				["YellOnBarrel"] = false,
				["Timer47310castTColor"] = 0,
				["Timer47340targetTColor"] = 0,
				["Enabled"] = true,
				["specWarnBrewSWNote"] = true,
				["announce47310cast"] = true,
			}, -- [1]
		},
		["Greench"] = {
			{
				["announce101873spell"] = true,
				["HealthFrame"] = false,
				["Timer101873cdTColor"] = 0,
				["SpecWarn101860moveSWNote"] = true,
				["Timer101885cdTColor"] = 0,
				["announce101938spell"] = true,
				["Timer101907castTColor"] = 0,
				["Timer101910cd"] = true,
				["Timer101910cdTColor"] = 3,
				["Enabled"] = true,
				["announce101910spell"] = true,
				["Timer101873cd"] = true,
				["Timer101938cd"] = true,
				["Timer101907cast"] = true,
				["Timer101885cd"] = true,
				["SpecWarn101860move"] = true,
				["announce101907cast"] = true,
				["SpecWarn101860moveSWSound"] = 1,
				["Timer101938cdTColor"] = 3,
			}, -- [1]
		},
		["PlantsVsZombies"] = {
			{
				["specWarnWave"] = true,
				["announce91739spell"] = false,
				["HealthFrame"] = false,
				["announce91834spell"] = false,
				["announce92228spell"] = true,
				["announce92606spell"] = true,
				["specWarnWaveSWNote"] = true,
				["specWarnWaveSWSound"] = 2,
				["warnTotalAdds"] = true,
				["Enabled"] = true,
			}, -- [1]
		},
		["talent1"] = "浩劫",
		["d285"] = {
			{
				["warnHorsemanHead"] = true,
				["announceother42380target"] = true,
				["warnHorsemanSoldiers"] = true,
				["Timer42514target2TColor"] = 0,
				["HealthFrame"] = false,
				["announceother42514target2"] = false,
				["WarnPhase"] = true,
				["Timer42380target"] = false,
				["Timer42514target2"] = false,
				["Enabled"] = true,
				["Timer42380targetTColor"] = 0,
			}, -- [1]
		},
		["Omen"] = {
			{
				["Enabled"] = true,
				["announce26540spell"] = true,
				["HealthFrame"] = false,
				["announce104903spell"] = true,
				["Timer26540cdTColor"] = 2,
				["Timer26540cd"] = true,
				["Timer104903cd"] = true,
				["SpecWarn26540moveSWNote"] = true,
				["SpecWarn26540move"] = true,
				["Timer104903cdTColor"] = 6,
				["SpecWarn26540moveSWSound"] = 1,
			}, -- [1]
		},
		["Brew"] = {
			{
				["NormalizeVolume"] = true,
				["HealthFrame"] = false,
				["Enabled"] = true,
			}, -- [1]
		},
	},
	["水牧丶-凯恩血蹄"] = {
		["d288"] = {
			[2] = {
				["Enabled"] = true,
				["TrioActiveTimer"] = true,
				["HealthFrame"] = false,
				["TrioActiveTimerTColor"] = 0,
				["announce68821cast"] = true,
				["SpecWarn68927moveSWSound"] = 1,
				["SpecWarn68927move"] = true,
				["SpecWarn68934moveSWSound"] = 1,
				["SpecWarn68927moveSWNote"] = true,
				["SpecWarn68934move"] = true,
				["Timer68821cast"] = false,
				["SpecWarn68934moveSWNote"] = true,
				["Timer68821castTColor"] = 0,
			},
		},
		["talent2"] = "神圣",
		["d286"] = {
			[2] = {
				["Enabled"] = true,
				["specWarnAttack"] = true,
				["HealthFrame"] = false,
				["specWarnAttackSWNote"] = true,
				["Emerged"] = true,
				["SubmergTimerTColor"] = 6,
				["EmergeTimerTColor"] = 6,
				["EmergeTimer"] = true,
				["announce37751spell"] = true,
				["specWarnAttackSWSound"] = 1,
				["SubmergTimer"] = true,
			},
		},
		["d287"] = {
			[2] = {
				["announceother51413target"] = true,
				["Timer47340target"] = false,
				["Timer51413target"] = true,
				["HealthFrame"] = false,
				["specWarnBrew"] = true,
				["specWarnBrewStun"] = true,
				["specWarnBrewStunSWNote"] = true,
				["Timer47310cast"] = true,
				["specWarnBrewStunSWSound"] = 1,
				["Timer47376targetTColor"] = 0,
				["Timer51413targetTColor"] = 0,
				["Timer47376target"] = false,
				["specWarnBrewSWSound"] = 1,
				["announce47310cast"] = false,
				["Timer47310castTColor"] = 0,
				["Timer47340targetTColor"] = 0,
				["Enabled"] = true,
				["specWarnBrewSWNote"] = true,
				["YellOnBarrel"] = false,
			},
		},
		["Greench"] = {
			[2] = {
				["announce101873spell"] = true,
				["HealthFrame"] = false,
				["Timer101873cdTColor"] = 0,
				["SpecWarn101860moveSWNote"] = true,
				["Timer101885cdTColor"] = 0,
				["announce101938spell"] = true,
				["Timer101907castTColor"] = 0,
				["Timer101910cd"] = true,
				["Timer101910cdTColor"] = 3,
				["Enabled"] = true,
				["announce101910spell"] = true,
				["Timer101873cd"] = true,
				["Timer101938cd"] = true,
				["Timer101938cdTColor"] = 3,
				["SpecWarn101860moveSWSound"] = 1,
				["announce101907cast"] = true,
				["SpecWarn101860move"] = true,
				["Timer101885cd"] = true,
				["Timer101907cast"] = true,
			},
		},
		["PlantsVsZombies"] = {
			[2] = {
				["specWarnWave"] = true,
				["announce91739spell"] = false,
				["HealthFrame"] = false,
				["announce91834spell"] = false,
				["announce92228spell"] = true,
				["announce92606spell"] = true,
				["Enabled"] = true,
				["specWarnWaveSWSound"] = 2,
				["warnTotalAdds"] = true,
				["specWarnWaveSWNote"] = true,
			},
		},
		["d285"] = {
			[2] = {
				["warnHorsemanHead"] = true,
				["announceother42380target"] = true,
				["warnHorsemanSoldiers"] = true,
				["Timer42514target2TColor"] = 0,
				["HealthFrame"] = false,
				["announceother42514target2"] = false,
				["WarnPhase"] = true,
				["Timer42380target"] = true,
				["Timer42514target2"] = false,
				["Enabled"] = true,
				["Timer42380targetTColor"] = 0,
			},
		},
		["Omen"] = {
			[2] = {
				["Enabled"] = true,
				["announce26540spell"] = true,
				["HealthFrame"] = false,
				["announce104903spell"] = true,
				["Timer26540cdTColor"] = 2,
				["Timer26540cd"] = true,
				["Timer104903cd"] = true,
				["SpecWarn26540moveSWNote"] = true,
				["SpecWarn26540move"] = true,
				["Timer104903cdTColor"] = 6,
				["SpecWarn26540moveSWSound"] = 1,
			},
		},
		["Brew"] = {
			[2] = {
				["NormalizeVolume"] = true,
				["Enabled"] = true,
				["HealthFrame"] = false,
			},
		},
	},
	["凛若-凯恩血蹄"] = {
		["d288"] = {
			[0] = {
				["Enabled"] = true,
				["Timer68821castTColor"] = 0,
				["HealthFrame"] = false,
				["TrioActiveTimerTColor"] = 0,
				["announce68821cast"] = true,
				["SpecWarn68927moveSWSound"] = 1,
				["SpecWarn68927move"] = true,
				["SpecWarn68934moveSWSound"] = 1,
				["SpecWarn68927moveSWNote"] = true,
				["Timer68821cast"] = true,
				["SpecWarn68934move"] = true,
				["SpecWarn68934moveSWNote"] = true,
				["TrioActiveTimer"] = true,
			},
		},
		["PlantsVsZombies"] = {
			[0] = {
				["specWarnWave"] = true,
				["specWarnWaveSWSound"] = 2,
				["HealthFrame"] = false,
				["announce91834spell"] = false,
				["specWarnWaveSWNote"] = true,
				["announce92606spell"] = true,
				["Enabled"] = true,
				["announce91739spell"] = false,
				["warnTotalAdds"] = true,
				["announce92228spell"] = true,
			},
		},
		["d286"] = {
			[0] = {
				["Enabled"] = true,
				["specWarnAttack"] = true,
				["HealthFrame"] = false,
				["SubmergTimer"] = true,
				["Emerged"] = true,
				["SubmergTimerTColor"] = 6,
				["specWarnAttackSWNote"] = true,
				["EmergeTimer"] = true,
				["EmergeTimerTColor"] = 6,
				["specWarnAttackSWSound"] = 1,
				["announce37751spell"] = true,
			},
		},
		["d287"] = {
			[0] = {
				["announceother51413target"] = true,
				["Timer47340target"] = true,
				["Timer51413target"] = true,
				["HealthFrame"] = false,
				["specWarnBrew"] = true,
				["specWarnBrewStun"] = true,
				["specWarnBrewStunSWNote"] = true,
				["Timer47310cast"] = true,
				["Enabled"] = true,
				["announce47310cast"] = false,
				["Timer51413targetTColor"] = 0,
				["YellOnBarrel"] = false,
				["specWarnBrewSWSound"] = 1,
				["Timer47376target"] = true,
				["Timer47376targetTColor"] = 0,
				["Timer47340targetTColor"] = 0,
				["Timer47310castTColor"] = 0,
				["specWarnBrewSWNote"] = true,
				["specWarnBrewStunSWSound"] = 1,
			},
		},
		["Omen"] = {
			[0] = {
				["Enabled"] = true,
				["announce26540spell"] = true,
				["HealthFrame"] = false,
				["Timer26540cd"] = true,
				["Timer26540cdTColor"] = 2,
				["announce104903spell"] = true,
				["Timer104903cd"] = true,
				["SpecWarn26540moveSWNote"] = true,
				["SpecWarn26540move"] = true,
				["Timer104903cdTColor"] = 6,
				["SpecWarn26540moveSWSound"] = 1,
			},
		},
		["d285"] = {
			[0] = {
				["Enabled"] = true,
				["announceother42380target"] = true,
				["warnHorsemanSoldiers"] = true,
				["Timer42514target2TColor"] = 0,
				["HealthFrame"] = false,
				["announceother42514target2"] = false,
				["WarnPhase"] = true,
				["Timer42380target"] = true,
				["Timer42514target2"] = false,
				["warnHorsemanHead"] = true,
				["Timer42380targetTColor"] = 0,
			},
		},
		["Brew"] = {
			[0] = {
				["NormalizeVolume"] = true,
				["Enabled"] = true,
				["HealthFrame"] = false,
			},
		},
		["Greench"] = {
			[0] = {
				["announce101873spell"] = true,
				["HealthFrame"] = false,
				["Timer101873cdTColor"] = 0,
				["SpecWarn101860moveSWNote"] = true,
				["Timer101885cdTColor"] = 0,
				["announce101938spell"] = true,
				["Timer101907castTColor"] = 0,
				["Timer101910cd"] = true,
				["Timer101907cast"] = true,
				["Enabled"] = true,
				["announce101910spell"] = true,
				["Timer101873cd"] = true,
				["announce101907cast"] = true,
				["Timer101885cd"] = true,
				["Timer101938cd"] = true,
				["SpecWarn101860move"] = true,
				["Timer101910cdTColor"] = 3,
				["SpecWarn101860moveSWSound"] = 1,
				["Timer101938cdTColor"] = 3,
			},
		},
	},
}
