
DBM_AllSavedOptions = {
	["Default"] = {
		["SpecialWarningFontSize"] = 50,
		["HUDTextureOverride"] = false,
		["DontShowFarWarnings"] = true,
		["ChosenVoicePack"] = "Yike",
		["DontShowHudMap2"] = false,
		["AlwaysPlayVoice"] = false,
		["ShowSWarningsInChat"] = true,
		["RangeFrameRadarY"] = 6.99998664855957,
		["HUDAlpha2"] = 0.5,
		["StatusEnabled"] = true,
		["DontRestoreIcons"] = false,
		["DontShowNameplateIcons"] = false,
		["RangeFrameX"] = 294.421508789063,
		["AlwaysShowSpeedKillTimer"] = true,
		["HUDColor2"] = {
			1, -- [1]
			0, -- [2]
			0, -- [3]
		},
		["FilterInterruptNoteName"] = false,
		["EnableModels"] = true,
		["SpecialWarningFlashAlph3"] = 0.4,
		["ArrowPoint"] = "TOP",
		["SWarnNameInNote"] = true,
		["DontShowPTCountdownText"] = false,
		["InfoFramePoint"] = "CENTER",
		["CRT_Enabled"] = false,
		["SpecialWarningFlashCol2"] = {
			1, -- [1]
			0.5, -- [2]
			0, -- [3]
		},
		["HUDColorOverride"] = false,
		["WarningFont"] = "Fonts\\ARKai_T.ttf",
		["CheckGear"] = true,
		["HUDColor4"] = {
			0, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["WorldBossAlert"] = false,
		["HUDSize3"] = 5,
		["DontShowPT2"] = false,
		["MCMessageShown"] = false,
		["HelpMessageVersion"] = 3,
		["DontSendBossWhispers"] = false,
		["UseMasterVolume"] = true,
		["DontShowSpecialWarnings"] = false,
		["HideWatchFrame"] = false,
		["SpamBlockBossWhispers"] = false,
		["ShowMinimapButton"] = true,
		["ShowGuildMessages"] = true,
		["ShowAdvSWSounds"] = false,
		["ShowQueuePop"] = true,
		["WarningPoint"] = "CENTER",
		["ForumsMessageShown"] = false,
		["ShowRecoveryMessage"] = true,
		["SpecialWarningFlashDura5"] = 1,
		["LTSpecialWarningFontColor"] = {
			0, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["ShowCombatLogMessage"] = true,
		["SpecialWarningFontCol"] = {
			1, -- [1]
			0.7, -- [2]
			0, -- [3]
		},
		["WarningAlphabetical"] = true,
		["SpecialWarningPoint"] = "CENTER",
		["WarningFontStyle"] = "None",
		["SpecialWarningSound"] = "Sound\\Spells\\PVPFlagTaken.ogg",
		["InfoFrameY"] = -124.695487976074,
		["ChatFrame"] = "DEFAULT_CHAT_FRAME",
		["HealthFrameLocked"] = false,
		["UseSoundChannel"] = "Master",
		["NewsMessageShown"] = 4,
		["SpecialWarningX"] = 0,
		["RangeFrameRadarX"] = -259.999847412109,
		["SpecialWarningDuration"] = 4,
		["RaidWarningPosition"] = {
			["Y"] = -185,
			["X"] = 0,
			["Point"] = "TOP",
		},
		["ShowShakeFrame"] = true,
		["HideQuestTooltips"] = true,
		["HUDAlpha1"] = 0.5,
		["LTSpecialWarningPoint"] = "CENTER",
		["SpecialWarningFlashAlph2"] = 0.3,
		["ShowSpecialWarnings"] = true,
		["DontShowPT"] = true,
		["SpecialWarningSound2"] = "Sound\\Spells\\PVPFlagTaken.ogg",
		["ShowCountdownText"] = false,
		["SpecialWarningFlashRepeat1"] = false,
		["HUDSize2"] = 5,
		["ShowFakedRaidWarnings"] = false,
		["LatencyThreshold"] = 250,
		["BlockVersionUpdateNotice"] = false,
		["DebugLevel"] = 1,
		["LFDEnhance"] = true,
		["SpecialWarningFlashDura1"] = 0.4,
		["DontShowPTNoID"] = false,
		["HideGarrisonToasts"] = true,
		["ArrowPosY"] = -150,
		["AdvancedAutologBosses"] = false,
		["SpecialWarningFontShadow"] = false,
		["HUDAlpha4"] = 0.5,
		["RLReadyCheckSound"] = true,
		["DontShowHealthFrame"] = false,
		["WOTLKTWMessageShown"] = false,
		["HideObjectivesFrame"] = false,
		["SpecialWarningFlashCol1"] = {
			1, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["SpecialWarningSound5"] = "Sound\\Creature\\Loathstare\\Loa_Naxx_Aggro02.ogg",
		["DontShowPTText"] = false,
		["HUDSize1"] = 5,
		["PTCountThreshold"] = 10,
		["SpecialWarningFontSize2"] = 40,
		["SpecialWarningFlashCol5"] = {
			0.2, -- [1]
			1, -- [2]
			1, -- [3]
		},
		["HUDTexture3"] = "highlight",
		["SWarnClassColor"] = true,
		["ShowRespawn"] = true,
		["ShowAllVersions"] = false,
		["InfoFrameLines"] = 0,
		["SpecialWarningFlashCol4"] = {
			1, -- [1]
			0, -- [2]
			1, -- [3]
		},
		["SpecialWarningFlashAlph4"] = 0.4,
		["WarningX"] = 0,
		["ChallengeBest"] = "Realm",
		["RangeFramePoint"] = "CENTER",
		["HUDTexture4"] = "highlight",
		["DontShowFlexMessage"] = false,
		["HUDSizeOverride"] = false,
		["dwSetDefault"] = 2,
		["CountdownVoice2"] = "VP:Yike",
		["AutoAcceptGuildInvite"] = false,
		["ShowLoadMessage"] = true,
		["ArrowPosX"] = 0,
		["LTSpecialWarningY"] = -130,
		["AITimer"] = true,
		["SpecialWarningFlashDura3"] = 1,
		["MovieFilter"] = "Never",
		["HPFramePoint"] = "CENTER",
		["WarningFontShadow"] = true,
		["ShowLTSpecialWarnings"] = true,
		["WarningDuration"] = 4,
		["SpecialWarningSound4"] = "Sound\\Creature\\HoodWolf\\HoodWolfTransformPlayer01.ogg",
		["DisableSFX"] = false,
		["AutologBosses"] = false,
		["SpecialWarningFlashDura4"] = 0.7,
		["SpecialWarningY"] = 75,
		["HUDAlphaOverride"] = false,
		["SpecialWarningFlashCol3"] = {
			1, -- [1]
			0, -- [2]
			0, -- [3]
		},
		["WarningColors"] = {
			{
				["b"] = 0.941176470588235,
				["g"] = 0.8,
				["r"] = 0.411764705882353,
			}, -- [1]
			{
				["b"] = 0,
				["g"] = 0.949019607843137,
				["r"] = 0.949019607843137,
			}, -- [2]
			{
				["b"] = 0,
				["g"] = 0.501960784313726,
				["r"] = 1,
			}, -- [3]
			{
				["b"] = 0.101960784313726,
				["g"] = 0.101960784313726,
				["r"] = 1,
			}, -- [4]
		},
		["ShowDefeatMessage"] = true,
		["SWarningAlphabetical"] = true,
		["SpecialWarningFontColor"] = {
			0.41, -- [1]
			0.8, -- [2]
			0.94, -- [3]
		},
		["BlockNoteShare"] = false,
		["ShowTranscriptorMessage"] = true,
		["CustomSounds"] = 0,
		["ShortTimerText"] = true,
		["ModelSoundValue"] = "Short",
		["HUDColor3"] = {
			1, -- [1]
			0.5, -- [2]
			0, -- [3]
		},
		["DontPlayCountdowns"] = false,
		["HUDTexture2"] = "highlight",
		["RangeFrameRadarPoint"] = "RIGHT",
		["DontShowInfoFrame"] = false,
		["HideBossEmoteFrame"] = true,
		["HUDAlpha3"] = 0.5,
		["RangeFrameUpdates"] = "Average",
		["AutoCorrectTimer"] = false,
		["ShowEngageMessage"] = true,
		["RaidWarningSound"] = "Sound\\Doodad\\BellTollNightElf.ogg",
		["DontRestoreRange"] = false,
		["AutoRespond"] = true,
		["SpecialWarningFlashRepeat3"] = true,
		["RoleSpecAlert"] = true,
		["WhisperStats"] = false,
		["VoiceOverSpecW2"] = "DefaultOnly",
		["RangeFrameSound1"] = "none",
		["DontPlayPTCountdown"] = false,
		["SpecialWarningFlashAlph5"] = 0.5,
		["ShowKillMessage"] = true,
		["HealthFrameWidth"] = 200,
		["DontShowUserTimers"] = false,
		["WarningIconLeft"] = true,
		["RangeFrameLocked"] = false,
		["HPFrameY"] = 146.361450195313,
		["WarningFontSize"] = 20,
		["CountdownVoice3"] = "Pewsey",
		["LTSpecialWarningFontSize"] = 50,
		["LastRevision"] = 10377,
		["CountdownVoice3v2"] = "VP:Yike",
		["SettingsMessageShown"] = true,
		["PGMessageShown"] = false,
		["HUDSize4"] = 5,
		["CountdownVoice"] = "Mosh",
		["FilterInterrupt"] = true,
		["DontSetIcons"] = false,
		["BigBrotherAnnounceToRaid"] = false,
		["SpecialWarningSound3"] = "Sound\\Spells\\PVPFlagTaken.ogg",
		["SpecialWarningFlashRepeat4"] = false,
		["FakeBWVersion"] = false,
		["FilterSelfHud"] = true,
		["SpecialWarningFlashRepeat2"] = false,
		["SpecialWarningFlashDura2"] = 0.4,
		["SpecialWarningFlashRepeat5"] = true,
		["DisableStatusWhisper"] = false,
		["HealthFrameGrowUp"] = false,
		["ShowAdvSWSound"] = true,
		["RangeFrameFrames"] = "text",
		["HUDTexture1"] = "highlight",
		["ShowBigBrotherOnCombatStart"] = false,
		["SpecialWarningIcon"] = true,
		["WarningY"] = 260,
		["SpecialWarningFlashAlph1"] = 0.3,
		["LTSpecialWarningX"] = 0,
		["FilterTankSpec"] = true,
		["DontShowRangeFrame"] = false,
		["ShowChatTime"] = true,
		["InfoFrameShowSelf"] = false,
		["SpecialWarningFont"] = "Fonts\\ARKai_T.ttf",
		["DebugMode"] = false,
		["ShowWarningsInChat"] = true,
		["DontShowBossTimers"] = false,
		["SpecialWarningFontStyle"] = "THICKOUTLINE",
		["SetPlayerRole"] = true,
		["AlwaysShowHealthFrame"] = false,
		["FilterDispel"] = true,
		["WorldBossNearAlert"] = false,
		["HPFrameMaxEntries"] = 5,
		["DontShowBossAnnounces"] = false,
		["SpecialWarningFlashRepeatAmount"] = 2,
		["AutoAcceptFriendInvite"] = false,
		["WarningIconChat"] = true,
		["AutoReplySound"] = true,
		["HideGuildChallengeUpdates"] = true,
		["DontShowCTCount"] = false,
		["DontSendYells"] = false,
		["ShowPizzaMessage"] = true,
		["RangeFrameSound2"] = "none",
		["HideTooltips"] = false,
		["WarningIconRight"] = true,
		["LTSpecialWarningFont"] = "Fonts\\ARKai_T.ttf",
		["Enabled"] = true,
		["MoviesSeen"] = {
		},
		["BCTWMessageShown"] = false,
		["HelpMessageShown"] = false,
		["HUDColor1"] = {
			1, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["BugMessageShown"] = 1,
		["ShowWipeMessage"] = true,
		["LogOnlyRaidBosses"] = false,
		["StripServerName"] = true,
		["FilterSayAndYell"] = false,
		["RangeFrameY"] = -232.174407958984,
		["HPFrameX"] = 384.659454345703,
		["InfoFrameX"] = 273.355438232422,
		["AFKHealthWarning"] = true,
		["CATATWMessageShown"] = false,
		["ShowFlashFrame"] = true,
	},
}
