
Duowan_CVar = {
	["凯恩血蹄__凛若"] = {
		["AtlasLootMod"] = {
			["AtlasLootEnable"] = 1,
		},
		["GatherMateModule"] = {
			["showTreasure"] = 1,
			["showMinimap"] = 1,
			["GatherMateEnable"] = 0,
		},
		["DWGKPMOD"] = {
			["reportChannel"] = "团队",
			["distrubuteGroup"] = "全团",
			["gkpEnable"] = 0,
			["showTitan"] = 1,
			["logQuality"] = "|cff0070dd蓝色品质|r",
		},
		["DuowanConfig"] = {
			["disableFilter"] = 1,
			["showAllEnemyDebuffs"] = 1,
		},
		["TheBurningTrade"] = {
			["TradeList"] = 1,
			["QuickTrade"] = 1,
			["AnnounceChannel"] = "密聊",
			["AnnounceTrade"] = 1,
			["EnableBuringTrade"] = 1,
		},
		["GridMod"] = {
			["GridEnable"] = 0,
		},
		["TinyTip"] = {
			["Guild"] = 1,
			["Talent"] = 1,
			["OverideDefault"] = 1,
			["ColorFriends"] = 1,
			["Fade"] = 0,
			["ShowTarget"] = 1,
			["StatusBarText"] = 1,
			["OffsetX"] = 30,
			["PvPRank"] = 0,
			["HoverLink"] = 1,
			["OffsetY"] = -30,
			["AnchorMethod"] = "跟随(2)",
			["ShowRange"] = 1,
		},
		["RangeDisplayHistry"] = {
			["LockPosition"] = 1,
			["RANDDISPLAY_ENABLED"] = 1,
		},
		["DecursiveMod"] = {
			["DecursiveEnable"] = 0,
		},
		["AuctionMod"] = {
			["EnableAuctionMod"] = 1,
			["AuctionInfo"] = 1,
		},
		["OmenMod"] = {
			["OmenEnable"] = 1,
		},
		["Action Button"] = {
			["AnchorPoint"] = "图标",
			["RedOut"] = 1,
			["LockCoolLine"] = 1,
			["EnableTCCCD"] = 1,
			["CenterIconName"] = 1,
			["EnableCoolLine"] = 1,
			["CenterIcon"] = 0,
		},
		["oRA3Mod"] = {
			["oRA3Enable"] = 0,
			["withRaid"] = 1,
		},
		["EquipSwitcher"] = {
			["ShownNumber"] = 4,
			["EQUIPSWITCHER_ENABLE2"] = 1,
			["EQUIPSWITCHER_RAID"] = 1,
			["EQUIPSWITCHER_ENABLE"] = 1,
		},
		["EN_UnitFrames"] = {
			["TargetFrameExtend"] = 1,
			["PartyExtend"] = 1,
			["ver"] = "3.1.3",
			["PlayerFrameXPBar"] = 1,
			["TOT"] = 1,
			["3DPortrait"] = 0,
			["showInRaid"] = 1,
			["TOTOT"] = 1,
			["PartyTarget"] = 1,
			["PartyBuff"] = 1,
			["PartyCast"] = 0,
			["FocusFrame"] = 1,
			["AutoHealthColor"] = 1,
			["TargetPercent"] = 1,
			["PlayerFrameExtend"] = 1,
		},
		["ITEMSHISTRY"] = {
			["StackSize"] = 1,
			["Tradeskill"] = 0,
			["itemLevel"] = 1,
			["DressUpSet"] = 1,
			["GemInfo"] = 1,
			["QulityText"] = 1,
			["SetInfo"] = 1,
			["EnableMendeleev"] = 1,
		},
		["ChatMod"] = {
			["ChatChannelEnable"] = 1,
			["WhisperPop"] = 1,
			["ReportStat"] = 1,
			["ChatPopoEnable"] = 1,
			["DuowanChatEnable"] = 1,
			["LFGForwarder"] = 1,
			["hideInRaid"] = 1,
			["ChatBarEnable"] = 1,
		},
		["MerchantAssist"] = {
			["AutoSellIgnor"] = 1,
			["OnlyInventory"] = 1,
			["EnableAutoSell"] = 1,
			["EnableAutoBuy"] = 1,
			["GuidBankFirst"] = 1,
			["EnableAutoRepair"] = 1,
		},
		["CliqueMod"] = {
			["CliqueEnable"] = 0,
		},
		["TRINKETHISTRY"] = {
			["TRINKET_OPTION1"] = 0,
		},
		["DuowanMoveMod"] = {
			["DuowanMoveEnable"] = 1,
			["BlizzMoveEnable"] = 1,
			["HideNone"] = 1,
		},
		["DWDKP"] = {
			["DWDKPEnable"] = 0,
		},
		["DuowanBar"] = {
			["DuowanBarAlwaysShow"] = 0,
			["curSkin"] = "可爱圆",
			["DuowanBarSkin"] = 0,
			["Gloss"] = 1,
			["DuowanBarHideTab"] = 0,
			["DuowanBarEnable"] = 0,
		},
		["MyInventory"] = {
			["EnableBank"] = 1,
			["EnableJPack"] = 1,
			["EnableBackPack"] = 1,
		},
		["RaidAlerterMod"] = {
			["RaidAlerterEnable"] = 0,
			["RaidAlerterLockPosition"] = 0,
		},
		["DBMMod"] = {
			["MovieBlock"] = 1,
			["DBMEnable"] = 1,
			["ShaOfFear"] = 1,
			["DBMSpellTimers"] = 0,
		},
		["TradeSkillMod"] = {
			["TradeTabs"] = 1,
			["TRADESKILL_OPTION1"] = 1,
			["ProfileColor"] = 1,
		},
		["ButtonFacade"] = {
			["debuffSin"] = "Dek2",
			["buttonSkin"] = "Blizzard",
			["buffSkin"] = "Dek2",
		},
		["LoveMod"] = {
			["EnableFriendMenu"] = 1,
			["LOOT_OPTION1"] = 1,
			["ShowQucikFocusTip"] = 1,
			["EnableImportFriend"] = 1,
			["LOOT_OPT"] = 1,
			["EnableQucikFocus"] = 1,
			["EnableMapNotes"] = 1,
			["EnableSmartTabard"] = 1,
			["EnableezIcon"] = 1,
		},
		["DenniCombatText"] = {
			["EnableDCT"] = 1,
			["DctSpellAlert"] = 0,
			["DctDamage"] = 0,
		},
		["HEALTHTEXT"] = {
			["EnableHealthText"] = 0,
			["ShowName"] = 0,
			["CastingBar"] = 1,
		},
		["LearningAid"] = {
			["MissingAbilities2"] = 0,
			["LockFrame"] = 0,
			["LearningAidEnable"] = 1,
			["Macros"] = 0,
			["ShapshiftForms"] = 0,
			["RrackingAblities"] = 0,
			["RestorAction"] = 1,
		},
		["QuestMod"] = {
			["AutoChoice"] = 1,
			["EnableAutoNotify"] = 1,
			["QuestPointer"] = 1,
			["EnableNotifyDetail"] = 1,
			["QuestHelperLiteEnable"] = 0,
			["LastSortType"] = 1,
			["EnableQuestFormat"] = 1,
			["WatchOnly"] = 0,
			["EnableDuowanQuest"] = 1,
			["AutoCollapse"] = 1,
			["QHubberEnableNew"] = 0,
			["SortType"] = 1,
			["AutoAdd"] = 1,
			["last_collapsed"] = 1,
			["AutoComplete"] = 0,
			["EnableTurnIn"] = 0,
		},
		["BuffTimer"] = {
			["ShowBuffCD"] = 1,
			["BuffTimerEnable"] = 1,
			["DisplayCaster"] = 1,
			["BuffSize"] = 23,
			["AnchorPoint"] = "正中",
			["SelfBuffOnly"] = 1,
			["BuffFacadeEnable"] = 1,
			["DisplayMount"] = 1,
			["AjustBuffSize"] = 1,
		},
		["TITANPANEL"] = {
			["enable"] = 1,
		},
		["ArenaMod"] = {
			["FireArena0"] = 0,
			["GladiatorlosSA"] = 1,
			["GladiusEnable"] = 1,
		},
		["BattleGroundMod"] = {
			["BattleInfoEnable"] = 1,
			["BattleInfoAutoLev"] = 1,
			["BattleInfoAutoRelease"] = 0,
			["BattleInfoShowHelp"] = 1,
			["BattleInfoIgLeft"] = 1,
			["BattleInfoShowStat"] = 1,
			["LevTime"] = 10,
		},
		["RecountMod"] = {
			["SkadaEnable"] = 1,
			["RecountEnable"] = 0,
		},
		["ChracterInfo"] = {
			["ItemLevelEnable"] = 1,
			["FizzleEnable"] = 1,
			["EnableRatingBusterNew"] = 0,
			["DUOWAN_CHARACTER_RATING"] = 1,
			["GearScoreLiteEnable2"] = 0,
			["FizzleRepairCost"] = 1,
			["EquipAttribute"] = 1,
			["EquipComareEnable"] = 1,
		},
		["DWPSMOD"] = {
			["RaidMarkEnable"] = 1,
			["ShowNotice"] = 0,
			["RaidMarkInParty"] = 1,
		},
		["ClassModule"] = {
			["EnableAspectBar"] = 1,
		},
		["PetBattleMod"] = {
			["EnableSort"] = 0,
			["EnableRareInfo"] = 1,
			["EnableFilter"] = 1,
		},
		["MiniMapMod"] = {
			["SEXYMAP_OPTION1"] = 1,
			["NPCScanEnable"] = 1,
			["MapsterEnable"] = 1,
			["ArchyEnable"] = 0,
			["NPCScanMinimap"] = 0,
			["EnableYssBossLoot"] = 1,
		},
		["AttackTimer"] = {
			["Order"] = 1,
			["AttackTimerEnable"] = 0,
			["CastDelayBarEnable"] = 1,
		},
		["EventAlertHistry"] = {
			["EVENTALERT_ENABLED"] = 1,
			["SpellAlertsDisable"] = 1,
			["EVENTALERT_LOCKFRAME"] = 1,
			["displaySpellID"] = 1,
		},
		["MySlotMod"] = {
			["MySlotTitanButton"] = 1,
			["EnableMySlotNew"] = 0,
		},
		["DuowanMod"] = {
			["EnableMaxCamara"] = 1,
			["EnableNewbieAssist"] = 0,
		},
		["ChannelClean"] = {
			["ChannelCleanEnable"] = 1,
		},
		["Accountant_Classic"] = {
			["EnableAccountant"] = 1,
		},
		["SpellTimer"] = {
			["SpellTimerEnable"] = 1,
		},
		["MAILMOD"] = {
			["EnableMailMod"] = 1,
			["Rake"] = 1,
			["BlackBook"] = 1,
			["Select"] = 1,
			["Wire"] = 1,
			["OpenAll"] = 1,
			["Express"] = 1,
		},
	},
}
Duowan_Frames = {
}
DUOWAN_VERSION = "5.4.0.4"
Duowan_PublicVar = {
	["凯恩血蹄"] = {
	},
}
