
tCD2DB = {
	["BUFF"] = {
		["long"] = false,
		["config"] = true,
		["hidecooldown"] = false,
		["font"] = "Fonts\\ARKai_T.TTF",
		["max"] = 0,
		["point"] = "CENTER",
		["alpha"] = 0.8,
		["size"] = 30,
	},
	["ACTION"] = {
		["hidecooldown"] = false,
		["scale"] = 4,
		["alpha"] = 0.8,
		["long"] = false,
		["config"] = true,
		["style"] = 0,
		["shine"] = true,
		["min"] = 2.99,
		["font"] = "Fonts\\ARKai_T.TTF",
		["size"] = 24,
	},
	["short"] = {
		["s"] = 1.1,
		["b"] = 0.12,
		["g"] = 0.12,
		["r"] = 1,
	},
	["mins"] = {
		["s"] = 0.7,
		["b"] = 0,
		["g"] = 0.6,
		["r"] = 0.8,
	},
	["secs"] = {
		["s"] = 1,
		["b"] = 0,
		["g"] = 0.8,
		["r"] = 1,
	},
	["center"] = {
		["r"] = 0,
		["b"] = 1,
		["text"] = false,
		["alpha"] = 1,
		["width"] = 100,
		["style"] = 1,
		["config"] = false,
		["time"] = 1.2,
		["position"] = {
			["y"] = 0,
			["p"] = "CENTER",
			["x"] = 0,
			["r"] = "CENTER",
		},
		["g"] = 1,
		["mode"] = true,
		["font"] = "Fonts\\ARKai_T.TTF",
		["size"] = 30,
	},
	["version"] = "30000.4",
	["redout"] = true,
	["hrs"] = {
		["s"] = 0.6,
		["b"] = 0,
		["g"] = 0.4,
		["r"] = 0.6,
	},
	["days"] = {
		["s"] = 0.6,
		["b"] = 0.4,
		["g"] = 0.4,
		["r"] = 0.4,
	},
	["bar"] = {
		["position"] = {
			["y"] = 0,
			["p"] = "CENTER",
			["x"] = 0,
			["r"] = "CENTER",
		},
		["font"] = "Fonts\\ARKai_T.TTF",
		["spacing"] = 5,
		["hidden"] = true,
		["width"] = 100,
		["min"] = 2.99,
		["config"] = false,
		["alpha"] = 0.9,
		["reverse"] = false,
		["locked"] = true,
		["height"] = 24,
		["sound"] = false,
		["size"] = 15,
	},
}
CoolLineDB = {
	["bgcolor"] = {
		["a"] = 0.6,
		["b"] = 0,
		["g"] = 0,
		["r"] = 0,
	},
	["border"] = "None",
	["h"] = 18,
	["fontsize"] = 14,
	["block"] = {
		["Hearthstone"] = true,
	},
	["iconplus"] = 4,
	["spellcolor"] = {
		["a"] = 1,
		["b"] = 0.8,
		["g"] = 0.78,
		["r"] = 0.23,
	},
	["nospellcolor"] = {
		["a"] = 1,
		["b"] = 0,
		["g"] = 0,
		["r"] = 0,
	},
	["inactivealpha"] = 0.1,
	["bordercolor"] = {
		["a"] = 1,
		["b"] = 1,
		["g"] = 1,
		["r"] = 1,
	},
	["w"] = 360,
	["y"] = -240,
	["x"] = 0,
	["dbinit"] = 2,
	["statusbar"] = "Gradient",
	["font"] = "Friz Quadrata TT",
	["fontcolor"] = {
		["a"] = 0.8,
		["b"] = 1,
		["g"] = 1,
		["r"] = 1,
	},
	["activealpha"] = 1,
}
