
TitanAll = {
	["TimerDualSpec"] = 2,
	["GlobalProfileUse"] = false,
	["TimerLDB"] = 2,
	["TimerAdjust"] = 1,
	["TimerVehicle"] = 1,
	["TimerPEW"] = 4,
	["GlobalProfileName"] = "<>",
}
TitanSettings = {
	["Players"] = {
		["凛若@凯恩血蹄"] = {
			["Panel"] = {
				["FontSize"] = 11,
				["ButtonAlign"] = 1,
				["Scale"] = 1,
				["ScreenAdjust"] = false,
				["ButtonSpacing"] = 20,
				["Bar2_Transparency"] = 0.7,
				["AuxTransparency"] = 0.7,
				["TexturePath"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Deep Cave Skin\\",
				["LockButtons"] = false,
				["BagAdjust"] = 1,
				["Buttons"] = {
					"Coords", -- [1]
					"XP", -- [2]
					"GoldTracker", -- [3]
					"Clock", -- [4]
					"Volume", -- [5]
					"AutoHide_Bar", -- [6]
					"Bag", -- [7]
					"Repair", -- [8]
					"Mail", -- [9]
					"Track", -- [10]
					"WinterTimer", -- [11]
					"TolBarad", -- [12]
				},
				["Bar_Transparency"] = 0.7,
				["FrameStrata"] = "BACKGROUND",
				["Bar2_Hide"] = false,
				["Transparency"] = 0.7,
				["AuxBar2_Align"] = 1,
				["Location"] = {
					"Bar", -- [1]
					"Bar", -- [2]
					"Bar", -- [3]
					"Bar", -- [4]
					"Bar", -- [5]
					"Bar", -- [6]
					"Bar", -- [7]
					"Bar", -- [8]
					"Bar", -- [9]
					"Bar", -- [10]
					"Bar", -- [11]
					"Bar", -- [12]
				},
				["TooltipFont"] = 1,
				["LockAutoHideInCombat"] = false,
				["AuxBar_Transparency"] = 0.7,
				["Bar2_Show"] = false,
				["AuxBar_Align"] = 1,
				["Bar_Show"] = true,
				["AuxBar2_Hide"] = false,
				["VersionShown"] = 1,
				["AuxBar2_Transparency"] = 0.7,
				["AuxScreenAdjust"] = false,
				["TooltipTrans"] = 1,
				["MinimapAdjust"] = false,
				["AuxBar2_Show"] = false,
				["TicketAdjust"] = 1,
				["IconSpacing"] = 0,
				["ToolTipsShown"] = 1,
				["FontName"] = "聊天",
				["Bar2_Align"] = 1,
				["HideTipsInCombat"] = false,
				["Bar_Hide"] = false,
				["Bar_Align"] = 1,
				["Position"] = 1,
				["AuxBar_Show"] = false,
				["DisableTooltipFont"] = 1,
				["AuxBar_Hide"] = false,
				["LogAdjust"] = false,
			},
			["Plugins"] = {
				["Track"] = {
					["DisplayOnRightSide"] = true,
					["CurrentTrackName"] = "无",
					["ShowIcon"] = 1,
					["ShowColoredText"] = 1,
				},
				["YssBossLoot"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = false,
				},
				["TolBarad"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["DisplayOnRightSide"] = false,
				},
				["LFGForwarder"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = false,
				},
				["TradeSkillInfo"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = false,
				},
				["AutoHide_Bar"] = {
					["DisplayOnRightSide"] = 1,
					["ForceBar"] = "Bar",
				},
				["AutoHide_AuxBar"] = {
					["DisplayOnRightSide"] = 1,
					["ForceBar"] = "AuxBar",
				},
				["LootType"] = {
					["ShowLabelText"] = 1,
					["RandomRoll"] = 100,
					["ShowIcon"] = 1,
					["ShowDungeonDiff"] = false,
				},
				["Performance"] = {
					["ShowAddonMemory"] = false,
					["ShowMemory"] = 1,
					["AddonMemoryType"] = 1,
					["ShowLatency"] = 1,
					["ShowLabelText"] = false,
					["ShowIcon"] = 1,
					["ShowAddonIncRate"] = false,
					["ShowColoredText"] = 1,
					["NumOfAddons"] = 5,
					["ShowFPS"] = 1,
				},
				["XP"] = {
					["ShowSimpleNumOfKills"] = false,
					["ShowIcon"] = 1,
					["ShowSimpleRested"] = false,
					["ShowSimpleToLevel"] = false,
					["DisplayType"] = "ShowXPPerHourSession",
					["ShowLabelText"] = 1,
				},
				["Skada"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = true,
					["DisplayOnRightSide"] = false,
					["ShowLabelText"] = true,
				},
				["AutoHide_Bar2"] = {
					["DisplayOnRightSide"] = 1,
					["ForceBar"] = "Bar2",
				},
				["AutoHide_AuxBar2"] = {
					["DisplayOnRightSide"] = 1,
					["ForceBar"] = "AuxBar2",
				},
				["AtlasLoot"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = false,
				},
				["Clock"] = {
					["OffsetHour"] = 0,
					["HideGameTimeMinimap"] = false,
					["DisplayOnRightSide"] = 1,
					["ShowColoredText"] = false,
					["Format"] = "12H",
					["TimeMode"] = "Server",
					["ShowLabelText"] = false,
				},
				["Volume"] = {
					["VolumeInboundChat"] = 1,
					["VolumeMaster"] = 0.7000000178813934,
					["VolumeSFX"] = 0.4000000357627869,
					["VolumeAmbience"] = 0.300000011920929,
					["VolumeMusic"] = 0.2000000476837158,
					["VolumeOutboundChat"] = 1,
					["OverrideBlizzSettings"] = false,
				},
				["Mail"] = {
					["HideMm"] = 1,
					["ShowButtonText"] = 1,
					["ShowIcon"] = 1,
					["ShowColoredText"] = 1,
					["ShowLabelText"] = 1,
				},
				["Repair"] = {
					["ShowColoredText"] = false,
					["IgnoreThrown"] = false,
					["AutoRepair"] = false,
					["DiscountFriendly"] = false,
					["ShowIcon"] = 1,
					["ShowDurabilityFrame"] = 1,
					["ShowUndamaged"] = false,
					["ShowMostDmgPer"] = 1,
					["DiscountRevered"] = false,
					["ShowInventory"] = 1,
					["UseGuildBank"] = false,
					["ShowNames"] = true,
					["ShowLabelText"] = 1,
					["DiscountExalted"] = false,
					["ShowRepairCost"] = 1,
					["ShowPercentage"] = false,
					["AutoRepairReport"] = false,
					["DiscountHonored"] = false,
					["ShowPopup"] = false,
					["ShowMostDamaged"] = false,
				},
				["WinterTimer"] = {
					["ShowColoredText"] = 1,
					["ShowIcon"] = 1,
					["DisplayOnRightSide"] = false,
				},
				["TitanRegen"] = {
					["ShowPercentage"] = false,
					["ShowColoredText"] = false,
					["ShowHPRegen"] = 1,
					["ShowMPRegen"] = 1,
					["ShowLabelText"] = 1,
				},
				["Bag"] = {
					["CountProfBagSlots"] = false,
					["ShowColoredText"] = 1,
					["CountShardBagSlots"] = false,
					["ShowUsedSlots"] = 1,
					["CountAmmoPouchSlots"] = false,
					["ShowIcon"] = 1,
					["ShowDetailedInfo"] = false,
					["ShowLabelText"] = 1,
				},
				["Omen"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = false,
				},
				["Coords"] = {
					["ShowColoredText"] = 1,
					["ShowZoneText"] = 1,
					["ShowLabelText"] = 1,
					["ShowIcon"] = 1,
					["ShowLocOnMiniMap"] = 1,
					["ShowCoordsOnMap"] = 1,
					["CoordsFormat2"] = false,
					["CoordsFormat1"] = 1,
					["CoordsFormat3"] = false,
				},
			},
			["Register"] = {
				["ToBeNum"] = 27,
				["TitanPlugins"] = {
					["Repair"] = {
						["builtIn"] = 1,
						["id"] = "Repair",
						["menuText"] = "修理",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowRepairCost"] = 1,
							["AutoRepair"] = false,
							["DiscountFriendly"] = false,
							["ShowIcon"] = 1,
							["ShowDurabilityFrame"] = 1,
							["ShowUndamaged"] = false,
							["ShowPercentage"] = false,
							["DiscountRevered"] = false,
							["ShowInventory"] = 1,
							["UseGuildBank"] = false,
							["ShowNames"] = true,
							["ShowLabelText"] = 1,
							["DiscountExalted"] = false,
							["ShowMostDmgPer"] = 1,
							["IgnoreThrown"] = false,
							["AutoRepairReport"] = false,
							["DiscountHonored"] = false,
							["ShowPopup"] = false,
							["ShowMostDamaged"] = false,
						},
						["version"] = "4.2.5.50000",
						["buttonTextFunction"] = "TitanPanelRepairButton_GetButtonText",
						["iconWidth"] = 16,
						["tooltipTextFunction"] = "TitanPanelRepairButton_GetTooltipText",
						["icon"] = "Interface\\AddOns\\Titan\\TitanRepair\\TitanRepair",
						["tooltipTitle"] = "耐久度信息",
					},
					["Bag"] = {
						["builtIn"] = 1,
						["id"] = "Bag",
						["menuText"] = "背包监视",
						["savedVariables"] = {
							["ShowColoredText"] = 1,
							["CountProfBagSlots"] = false,
							["CountShardBagSlots"] = false,
							["ShowUsedSlots"] = 1,
							["CountAmmoPouchSlots"] = false,
							["ShowIcon"] = 1,
							["ShowDetailedInfo"] = false,
							["ShowLabelText"] = 1,
						},
						["version"] = "4.2.5.50000",
						["buttonTextFunction"] = "TitanPanelBagButton_GetButtonText",
						["iconWidth"] = 16,
						["tooltipTextFunction"] = "TitanPanelBagButton_GetTooltipText",
						["icon"] = "Interface\\AddOns\\Titan\\TitanBag\\TitanBag",
						["tooltipTitle"] = "背包状态",
					},
					["TolBarad"] = {
						["builtIn"] = 1,
						["id"] = "TolBarad",
						["menuText"] = "托尔巴拉德计时",
						["savedVariables"] = {
							["ShowColoredText"] = 1,
							["ShowIcon"] = 1,
							["DisplayOnRightSide"] = false,
						},
						["version"] = "4.2.5.50000",
						["buttonTextFunction"] = "TitanTolBaradButton_GetButtonText",
						["iconWidth"] = 16,
						["tooltipTextFunction"] = "TitanTolBaradButton_GetTooltipText",
						["icon"] = "Interface\\Icons\\Ability_DualWield",
						["tooltipTitle"] = "托尔巴拉德计时器",
					},
					["Coords"] = {
						["builtIn"] = 1,
						["id"] = "Coords",
						["menuText"] = "坐标",
						["savedVariables"] = {
							["ShowColoredText"] = 1,
							["ShowZoneText"] = 1,
							["ShowLabelText"] = 1,
							["ShowIcon"] = 1,
							["CoordsFormat3"] = false,
							["CoordsFormat1"] = 1,
							["CoordsFormat2"] = false,
							["ShowCoordsOnMap"] = 1,
							["ShowLocOnMiniMap"] = 1,
						},
						["version"] = "4.2.5.50000",
						["buttonTextFunction"] = "TitanPanelCoordsButton_GetButtonText",
						["iconWidth"] = 16,
						["tooltipTextFunction"] = "TitanPanelCoordsButton_GetTooltipText",
						["icon"] = "Interface\\AddOns\\Titan\\TitanCoords\\TitanCoords",
						["tooltipTitle"] = "所在位置信息",
					},
					["TradeSkillInfo"] = {
						["notes"] = "",
						["iconWidth"] = 16,
						["id"] = "TradeSkillInfo",
						["menuText"] = "TSI",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = false,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["version"] = "v2.2.4",
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "launcher",
						["icon"] = "Interface\\Icons\\INV_Elemental_Mote_Nether",
						["LDBVariables"] = {
							["type"] = "launcher",
							["name"] = "TradeSkillInfo",
							["suffix"] = "",
							["value"] = "",
							["text"] = "",
							["label"] = "TSI",
						},
					},
					["AutoHide_Bar"] = {
						["savedVariables"] = {
							["DisplayOnRightSide"] = 1,
							["ForceBar"] = "Bar",
						},
						["version"] = "4.2.5.50000",
						["category"] = "Built-ins",
						["id"] = "AutoHide_Bar",
						["menuText"] = "AutoHide_Bar",
						["tooltipTitle"] = "面板自动隐藏 开/关",
					},
					["AutoHide_AuxBar"] = {
						["savedVariables"] = {
							["DisplayOnRightSide"] = 1,
							["ForceBar"] = "AuxBar",
						},
						["version"] = "4.2.5.50000",
						["category"] = "Built-ins",
						["id"] = "AutoHide_AuxBar",
						["menuText"] = "AutoHide_AuxBar",
						["tooltipTitle"] = "面板自动隐藏 开/关",
					},
					["LootType"] = {
						["builtIn"] = 1,
						["id"] = "LootType",
						["menuText"] = "分配方式",
						["savedVariables"] = {
							["ShowDungeonDiff"] = false,
							["RandomRoll"] = 100,
							["ShowIcon"] = 1,
							["ShowLabelText"] = 1,
						},
						["version"] = "4.2.5.50000",
						["buttonTextFunction"] = "TitanPanelLootTypeButton_GetButtonText",
						["iconWidth"] = 16,
						["tooltipTextFunction"] = "TitanPanelLootTypeButton_GetTooltipText",
						["icon"] = "Interface\\AddOns\\Titan\\TitanLootType\\TitanLootType",
						["tooltipTitle"] = "分配方式",
					},
					["Performance"] = {
						["builtIn"] = 1,
						["id"] = "Performance",
						["menuText"] = "性能",
						["savedVariables"] = {
							["ShowAddonMemory"] = false,
							["ShowMemory"] = 1,
							["AddonMemoryType"] = 1,
							["ShowLatency"] = 1,
							["ShowLabelText"] = false,
							["ShowIcon"] = 1,
							["ShowAddonIncRate"] = false,
							["ShowColoredText"] = 1,
							["NumOfAddons"] = 5,
							["ShowFPS"] = 1,
						},
						["version"] = "4.2.5.50000",
						["buttonTextFunction"] = "TitanPanelPerformanceButton_GetButtonText",
						["iconWidth"] = 16,
						["icon"] = "Interface\\AddOns\\Titan\\TitanPerformance\\TitanPerformance",
						["tooltipCustomFunction"] = nil --[[ skipped inline function ]],
					},
					["XP"] = {
						["builtIn"] = 1,
						["id"] = "XP",
						["menuText"] = "经验",
						["savedVariables"] = {
							["ShowSimpleNumOfKills"] = false,
							["ShowIcon"] = 1,
							["ShowSimpleRested"] = false,
							["ShowSimpleToLevel"] = false,
							["ShowLabelText"] = 1,
							["DisplayType"] = "ShowXPPerHourSession",
						},
						["version"] = "4.2.5.50000",
						["buttonTextFunction"] = "TitanPanelXPButton_GetButtonText",
						["iconWidth"] = 16,
						["tooltipTextFunction"] = "TitanPanelXPButton_GetTooltipText",
						["tooltipTitle"] = "经验相关信息",
					},
					["GoldTracker"] = {
						["buttonTextFunction"] = "TitanPanelGoldTrackerButton_GetButtonText",
						["version"] = "4.2.5.50000",
						["builtIn"] = 1,
						["id"] = "GoldTracker",
						["menuText"] = "金币助手",
						["tooltipTextFunction"] = "TitanPanelGoldTrackerButton_GetTooltipText",
						["tooltipTitle"] = "金币信息",
					},
					["Skada"] = {
						["notes"] = "\nWill be registered as single LDB plugin after the normal registration.",
						["iconWidth"] = 16,
						["id"] = "Skada",
						["menuText"] = "Skada",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = true,
							["DisplayOnRightSide"] = false,
							["ShowLabelText"] = true,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = true,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["version"] = "1.4-11",
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "data source",
						["icon"] = "Interface\\Icons\\Spell_Lightning_LightningBolt01",
						["LDBVariables"] = {
							["type"] = "data source",
							["name"] = "Skada",
							["suffix"] = "",
							["value"] = "",
							["text"] = "n/a",
							["label"] = "Skada",
						},
					},
					["AutoHide_Bar2"] = {
						["savedVariables"] = {
							["DisplayOnRightSide"] = 1,
							["ForceBar"] = "Bar2",
						},
						["version"] = "4.2.5.50000",
						["category"] = "Built-ins",
						["id"] = "AutoHide_Bar2",
						["menuText"] = "AutoHide_Bar2",
						["tooltipTitle"] = "面板自动隐藏 开/关",
					},
					["Volume"] = {
						["builtIn"] = 1,
						["id"] = "Volume",
						["menuText"] = "音量控制",
						["savedVariables"] = {
							["OverrideBlizzSettings"] = false,
							["VolumeMaster"] = 1,
							["VolumeSFX"] = 0.5,
							["VolumeInboundChat"] = 1,
							["VolumeMusic"] = 0.5,
							["VolumeOutboundChat"] = 1,
							["VolumeAmbience"] = 0.5,
						},
						["version"] = "4.2.5.50000",
						["iconButtonWidth"] = 18,
						["iconWidth"] = 32,
						["tooltipTextFunction"] = "TitanPanelVolumeButton_GetTooltipText",
						["tooltipTitle"] = "音量信息",
					},
					["AtlasLoot"] = {
						["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!\nWill be registered as single LDB plugin after the normal registration.",
						["iconWidth"] = 16,
						["id"] = "AtlasLoot",
						["menuText"] = "AtlasLoot",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = false,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "launcher",
						["icon"] = "Interface\\Icons\\INV_Box_01",
						["LDBVariables"] = {
							["type"] = "launcher",
							["name"] = "AtlasLoot",
							["suffix"] = "",
							["value"] = "",
							["text"] = "",
							["label"] = "AtlasLoot",
						},
					},
					["LFGForwarder"] = {
						["notes"] = "",
						["iconWidth"] = 16,
						["id"] = "LFGForwarder",
						["menuText"] = "LFGForwarder",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = false,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["iconCoords"] = {
							0.025, -- [1]
							0.1, -- [2]
							0.05, -- [3]
							0.2, -- [4]
						},
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "launcher",
						["icon"] = "Interface\\LFGFrame\\LFG-Eye",
						["LDBVariables"] = {
							["type"] = "launcher",
							["name"] = "LFGForwarder",
							["suffix"] = "",
							["value"] = "",
							["text"] = "",
							["label"] = "",
						},
					},
					["YssBossLoot"] = {
						["notes"] = "",
						["iconWidth"] = 16,
						["id"] = "YssBossLoot",
						["menuText"] = "|cFF33FF99YssBossLoot|r",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = false,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["version"] = "",
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "launcher",
						["icon"] = "Interface\\Addons\\YssBossLoot\\Art\\skullwhite",
						["LDBVariables"] = {
							["type"] = "launcher",
							["name"] = "YssBossLoot",
							["suffix"] = "",
							["value"] = "",
							["text"] = "YssBossLoot",
							["label"] = "|cFF33FF99YssBossLoot|r",
						},
					},
					["Track"] = {
						["builtIn"] = 1,
						["id"] = "Track",
						["menuText"] = "追踪",
						["savedVariables"] = {
							["CurrentTrackName"] = "无",
							["ShowColoredText"] = 1,
							["ShowIcon"] = 1,
							["DisplayOnRightSide"] = true,
						},
						["version"] = "4.2.5.50000",
						["iconWidth"] = 16,
						["tooltipTextFunction"] = "TitanPanelTrackButton_GetTooltipText",
						["icon"] = "Interface\\Minimap\\Tracking\\None",
						["tooltipTitle"] = "追踪资讯",
					},
					["AutoHide_AuxBar2"] = {
						["savedVariables"] = {
							["DisplayOnRightSide"] = 1,
							["ForceBar"] = "AuxBar2",
						},
						["version"] = "4.2.5.50000",
						["category"] = "Built-ins",
						["id"] = "AutoHide_AuxBar2",
						["menuText"] = "AutoHide_AuxBar2",
						["tooltipTitle"] = "面板自动隐藏 开/关",
					},
					["WinterTimer"] = {
						["builtIn"] = 1,
						["id"] = "WinterTimer",
						["menuText"] = "冬拥湖计时",
						["savedVariables"] = {
							["ShowColoredText"] = 1,
							["ShowIcon"] = 1,
							["DisplayOnRightSide"] = false,
						},
						["version"] = "4.2.5.50000",
						["buttonTextFunction"] = "TitanWinterTimerButton_GetButtonText",
						["iconWidth"] = 16,
						["tooltipTextFunction"] = "TitanWinterTimerButton_GetTooltipText",
						["icon"] = "Interface\\Icons\\Spell_Frost_WizardMark",
						["tooltipTitle"] = "冬拥湖计时器",
					},
					["TitanRegen"] = {
						["savedVariables"] = {
							["ShowMPRegen"] = 1,
							["ShowColoredText"] = false,
							["ShowHPRegen"] = 1,
							["ShowPercentage"] = false,
							["ShowLabelText"] = 1,
						},
						["tooltipTextFunction"] = "TitanPanelTitanRegenButton_GetTooltipText",
						["version"] = "4.2.5.50000",
						["builtIn"] = 1,
						["id"] = "TitanRegen",
						["menuText"] = "恢复",
						["buttonTextFunction"] = "TitanPanelTitanRegenButton_GetButtonText",
						["tooltipTitle"] = "恢复速度",
					},
					["Mail"] = {
						["builtIn"] = 1,
						["id"] = "Mail",
						["menuText"] = "邮件",
						["savedVariables"] = {
							["HideMm"] = 1,
							["ShowColoredText"] = 1,
							["ShowIcon"] = 1,
							["ShowButtonText"] = 1,
							["ShowLabelText"] = 1,
						},
						["version"] = "4.2.5.50000",
						["buttonTextFunction"] = "TitanPanelMailButton_GetButtonText",
						["iconWidth"] = 16,
						["tooltipTextFunction"] = "TitanPanelMailButton_GetTooltipText",
						["icon"] = "Interface\\AddOns\\Titan\\TitanMail\\nomail",
						["tooltipTitle"] = "邮件资讯",
					},
					["Omen"] = {
						["notes"] = "\nWill be registered as single LDB plugin after the normal registration.",
						["iconWidth"] = 16,
						["id"] = "Omen",
						["menuText"] = "Omen",
						["category"] = "Combat",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = false,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["version"] = "3.1.2",
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "launcher",
						["icon"] = "Interface\\AddOns\\Omen\\icon",
						["LDBVariables"] = {
							["type"] = "launcher",
							["name"] = "Omen",
							["suffix"] = "",
							["value"] = "",
							["text"] = "",
							["label"] = "",
						},
					},
					["Clock"] = {
						["savedVariables"] = {
							["OffsetHour"] = 0,
							["ShowColoredText"] = false,
							["DisplayOnRightSide"] = 1,
							["HideGameTimeMinimap"] = false,
							["Format"] = "12H",
							["TimeMode"] = "Server",
							["ShowLabelText"] = false,
						},
						["tooltipTextFunction"] = "TitanPanelClockButton_GetTooltipText",
						["version"] = "4.2.5.50000",
						["builtIn"] = 1,
						["id"] = "Clock",
						["menuText"] = "时钟",
						["buttonTextFunction"] = "TitanPanelClockButton_GetButtonText",
						["tooltipTitle"] = "时钟",
					},
				},
				["ToBe"] = {
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["savedVariables"] = {
									["DisplayOnRightSide"] = 1,
									["ForceBar"] = "Bar",
								},
								["version"] = "4.2.5.50000",
								["category"] = "Built-ins",
								["id"] = "AutoHide_Bar",
								["menuText"] = "AutoHide_Bar",
								["tooltipTitle"] = "面板自动隐藏 开/关",
							},
							["tooltipTitle"] = "面板自动隐藏 开/关",
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "AutoHide_Bar",
						["category"] = "Built-ins",
						["button"] = "TitanPanelAutoHide_BarButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [1]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["savedVariables"] = {
									["DisplayOnRightSide"] = 1,
									["ForceBar"] = "Bar2",
								},
								["version"] = "4.2.5.50000",
								["category"] = "Built-ins",
								["id"] = "AutoHide_Bar2",
								["menuText"] = "AutoHide_Bar2",
								["tooltipTitle"] = "面板自动隐藏 开/关",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "AutoHide_Bar2",
						["category"] = "Built-ins",
						["button"] = "TitanPanelAutoHide_Bar2Button",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [2]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["savedVariables"] = {
									["DisplayOnRightSide"] = 1,
									["ForceBar"] = "AuxBar2",
								},
								["version"] = "4.2.5.50000",
								["category"] = "Built-ins",
								["id"] = "AutoHide_AuxBar2",
								["menuText"] = "AutoHide_AuxBar2",
								["tooltipTitle"] = "面板自动隐藏 开/关",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "AutoHide_AuxBar2",
						["category"] = "Built-ins",
						["button"] = "TitanPanelAutoHide_AuxBar2Button",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [3]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["savedVariables"] = {
									["DisplayOnRightSide"] = 1,
									["ForceBar"] = "AuxBar",
								},
								["version"] = "4.2.5.50000",
								["category"] = "Built-ins",
								["id"] = "AutoHide_AuxBar",
								["menuText"] = "AutoHide_AuxBar",
								["tooltipTitle"] = "面板自动隐藏 开/关",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "AutoHide_AuxBar",
						["category"] = "Built-ins",
						["button"] = "TitanPanelAutoHide_AuxBarButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [4]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["builtIn"] = 1,
								["id"] = "Bag",
								["menuText"] = "背包监视",
								["savedVariables"] = {
									["ShowColoredText"] = 1,
									["CountProfBagSlots"] = false,
									["CountShardBagSlots"] = false,
									["ShowUsedSlots"] = 1,
									["CountAmmoPouchSlots"] = false,
									["ShowIcon"] = 1,
									["ShowDetailedInfo"] = false,
									["ShowLabelText"] = 1,
								},
								["version"] = "4.2.5.50000",
								["buttonTextFunction"] = "TitanPanelBagButton_GetButtonText",
								["iconWidth"] = 16,
								["tooltipTextFunction"] = "TitanPanelBagButton_GetTooltipText",
								["icon"] = "Interface\\AddOns\\Titan\\TitanBag\\TitanBag",
								["tooltipTitle"] = "背包状态",
							},
							["tooltipText"] = "|cff20ff20提示: 左键点击打开所有背包.|r",
							["tooltipTitle"] = "背包状态",
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Bag",
						["category"] = "General",
						["button"] = "TitanPanelBagButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [5]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["savedVariables"] = {
									["OffsetHour"] = 0,
									["ShowColoredText"] = false,
									["DisplayOnRightSide"] = 1,
									["HideGameTimeMinimap"] = false,
									["Format"] = "12H",
									["TimeMode"] = "Server",
									["ShowLabelText"] = false,
								},
								["tooltipTextFunction"] = "TitanPanelClockButton_GetTooltipText",
								["version"] = "4.2.5.50000",
								["builtIn"] = 1,
								["id"] = "Clock",
								["menuText"] = "时钟",
								["buttonTextFunction"] = "TitanPanelClockButton_GetButtonText",
								["tooltipTitle"] = "时钟",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Clock",
						["category"] = "General",
						["button"] = "TitanPanelClockButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [6]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["builtIn"] = 1,
								["id"] = "Coords",
								["menuText"] = "坐标",
								["savedVariables"] = {
									["ShowColoredText"] = 1,
									["ShowZoneText"] = 1,
									["ShowLabelText"] = 1,
									["ShowIcon"] = 1,
									["CoordsFormat3"] = false,
									["CoordsFormat1"] = 1,
									["CoordsFormat2"] = false,
									["ShowCoordsOnMap"] = 1,
									["ShowLocOnMiniMap"] = 1,
								},
								["version"] = "4.2.5.50000",
								["buttonTextFunction"] = "TitanPanelCoordsButton_GetButtonText",
								["iconWidth"] = 16,
								["tooltipTextFunction"] = "TitanPanelCoordsButton_GetTooltipText",
								["icon"] = "Interface\\AddOns\\Titan\\TitanCoords\\TitanCoords",
								["tooltipTitle"] = "所在位置信息",
							},
							["px"] = 0.2475355267524719,
							["py"] = 0.5326917171478272,
							["tooltipText"] = "区域: 	|cffffffff翡翠林|r\n具体地点: 	|cffffffff浊水河岸|r\nPVP 信息: 	|cffff2020（争夺中的领土）|r\n\n|cffffffff炉石位置|r\n旅店: 	|cffffffff天神庭院|r\n|cff20ff20提示: Shift + 左键单击添加所在位置|r\n|cff20ff20信息到聊天窗口.|r",
							["subZoneText"] = "浊水河岸",
							["factionName"] = "",
							["tooltipTitle"] = "所在位置信息",
							["pvpType"] = "contested",
							["zoneText"] = "翡翠林",
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Coords",
						["category"] = "General",
						["button"] = "TitanPanelCoordsButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [7]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["tooltipText"] = "|cffff0000统计所持有金币信息 : 凯恩血蹄 : 部落|r\n凛若	|cffffffff113897金, 60银, 41铜|r\n--------------------\n总金币	|cffffffff113897金, 60银, 41铜|r\n\n|cffffffff周期统计|r\n起始金币数	|cff6666ff113897金, 60银, 41铜|r\n这个周期所赚金币	|cff00ff000金, 00银, 00铜|r\n每小时所赚金币	|cff00ff000金, 00银, 00铜|r",
							["tooltipTitle"] = "金币信息",
						},
						["notes"] = "",
						["plugin_type"] = "",
						["name"] = "TitanPanelGoldTrackerButtonCopperButton<child>",
						["category"] = "",
						["button"] = "TitanPanelGoldTrackerButtonCopperButton",
						["issue"] = "",
						["isChild"] = true,
						["status"] = "|cff20ff20Registered|r",
					}, -- [8]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["tooltipText"] = "|cffff0000统计所持有金币信息 : 凯恩血蹄 : 部落|r\n凛若	|cffffffff113897金, 60银, 41铜|r\n--------------------\n总金币	|cffffffff113897金, 60银, 41铜|r\n\n|cffffffff周期统计|r\n起始金币数	|cff6666ff113897金, 60银, 41铜|r\n这个周期所赚金币	|cff00ff000金, 00银, 00铜|r\n每小时所赚金币	|cff00ff000金, 00银, 00铜|r",
							["tooltipTitle"] = "金币信息",
						},
						["notes"] = "",
						["plugin_type"] = "",
						["name"] = "TitanPanelGoldTrackerButtonSilverButton<child>",
						["category"] = "",
						["button"] = "TitanPanelGoldTrackerButtonSilverButton",
						["issue"] = "",
						["isChild"] = true,
						["status"] = "|cff20ff20Registered|r",
					}, -- [9]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["tooltipText"] = "|cffff0000统计所持有金币信息 : 凯恩血蹄 : 部落|r\n凛若	|cffffffff113897金, 60银, 41铜|r\n--------------------\n总金币	|cffffffff113897金, 60银, 41铜|r\n\n|cffffffff周期统计|r\n起始金币数	|cff6666ff113897金, 60银, 41铜|r\n这个周期所赚金币	|cff00ff000金, 00银, 00铜|r\n每小时所赚金币	|cff00ff000金, 00银, 00铜|r",
							["tooltipTitle"] = "金币信息",
						},
						["notes"] = "",
						["plugin_type"] = "",
						["name"] = "TitanPanelGoldTrackerButtonGoldButton<child>",
						["category"] = "",
						["button"] = "TitanPanelGoldTrackerButtonGoldButton",
						["issue"] = "",
						["isChild"] = true,
						["status"] = "|cff20ff20Registered|r",
					}, -- [10]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["buttonTextFunction"] = "TitanPanelGoldTrackerButton_GetButtonText",
								["version"] = "4.2.5.50000",
								["builtIn"] = 1,
								["id"] = "GoldTracker",
								["menuText"] = "金币助手",
								["tooltipTextFunction"] = "TitanPanelGoldTrackerButton_GetTooltipText",
								["tooltipTitle"] = "金币信息",
							},
							["vadjust"] = 2,
							["moneyType"] = "PLAYER",
							["info"] = {
								["collapse"] = 1,
								["canPickup"] = 1,
								["showSmallerCoins"] = "Backpack",
								["PickupFunc"] = nil --[[ skipped inline function ]],
								["UpdateFunc"] = nil --[[ skipped inline function ]],
								["DropFunc"] = nil --[[ skipped inline function ]],
							},
							["tooltipText"] = "|cffff0000统计所持有金币信息 : 凯恩血蹄 : 部落|r\n凛若	|cffffffff113897金, 60银, 41铜|r\n--------------------\n总金币	|cffffffff113897金, 60银, 41铜|r\n\n|cffffffff周期统计|r\n起始金币数	|cff6666ff113897金, 60银, 41铜|r\n这个周期所赚金币	|cff00ff000金, 00银, 00铜|r\n每小时所赚金币	|cff00ff000金, 00银, 00铜|r",
							["small"] = 1,
							["staticMoney"] = 1138976041,
							["tooltipTitle"] = "金币信息",
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "GoldTracker",
						["category"] = "General",
						["button"] = "TitanPanelGoldTrackerButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [11]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["builtIn"] = 1,
								["id"] = "LootType",
								["menuText"] = "分配方式",
								["savedVariables"] = {
									["ShowDungeonDiff"] = false,
									["RandomRoll"] = 100,
									["ShowIcon"] = 1,
									["ShowLabelText"] = 1,
								},
								["version"] = "4.2.5.50000",
								["buttonTextFunction"] = "TitanPanelLootTypeButton_GetButtonText",
								["iconWidth"] = 16,
								["tooltipTextFunction"] = "TitanPanelLootTypeButton_GetTooltipText",
								["icon"] = "Interface\\AddOns\\Titan\\TitanLootType\\TitanLootType",
								["tooltipTitle"] = "分配方式",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "LootType",
						["category"] = "General",
						["button"] = "TitanPanelLootTypeButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [12]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["builtIn"] = 1,
								["id"] = "Performance",
								["menuText"] = "性能",
								["savedVariables"] = {
									["ShowAddonMemory"] = false,
									["ShowMemory"] = 1,
									["AddonMemoryType"] = 1,
									["ShowLatency"] = 1,
									["ShowLabelText"] = false,
									["ShowIcon"] = 1,
									["ShowAddonIncRate"] = false,
									["ShowColoredText"] = 1,
									["NumOfAddons"] = 5,
									["ShowFPS"] = 1,
								},
								["version"] = "4.2.5.50000",
								["buttonTextFunction"] = "TitanPanelPerformanceButton_GetButtonText",
								["iconWidth"] = 16,
								["icon"] = "Interface\\AddOns\\Titan\\TitanPerformance\\TitanPerformance",
								["tooltipCustomFunction"] = nil --[[ skipped inline function ]],
							},
							["fpsSampleCount"] = 0,
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Performance",
						["category"] = "General",
						["button"] = "TitanPanelPerformanceButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [13]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["savedVariables"] = {
									["ShowMPRegen"] = 1,
									["ShowColoredText"] = false,
									["ShowHPRegen"] = 1,
									["ShowPercentage"] = false,
									["ShowLabelText"] = 1,
								},
								["tooltipTextFunction"] = "TitanPanelTitanRegenButton_GetTooltipText",
								["version"] = "4.2.5.50000",
								["builtIn"] = 1,
								["id"] = "TitanRegen",
								["menuText"] = "恢复",
								["buttonTextFunction"] = "TitanPanelTitanRegenButton_GetButtonText",
								["tooltipTitle"] = "恢复速度",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "TitanRegen",
						["category"] = "General",
						["button"] = "TitanPanelTitanRegenButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [14]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["builtIn"] = 1,
								["id"] = "Repair",
								["menuText"] = "修理",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowRepairCost"] = 1,
									["AutoRepair"] = false,
									["DiscountFriendly"] = false,
									["ShowIcon"] = 1,
									["ShowDurabilityFrame"] = 1,
									["ShowUndamaged"] = false,
									["ShowPercentage"] = false,
									["DiscountRevered"] = false,
									["ShowInventory"] = 1,
									["UseGuildBank"] = false,
									["ShowNames"] = true,
									["ShowLabelText"] = 1,
									["DiscountExalted"] = false,
									["ShowMostDmgPer"] = 1,
									["IgnoreThrown"] = false,
									["AutoRepairReport"] = false,
									["DiscountHonored"] = false,
									["ShowPopup"] = false,
									["ShowMostDamaged"] = false,
								},
								["version"] = "4.2.5.50000",
								["buttonTextFunction"] = "TitanPanelRepairButton_GetButtonText",
								["iconWidth"] = 16,
								["tooltipTextFunction"] = "TitanPanelRepairButton_GetTooltipText",
								["icon"] = "Interface\\AddOns\\Titan\\TitanRepair\\TitanRepair",
								["tooltipTitle"] = "耐久度信息",
							},
							["tooltipText"] = "\n没有需要修理的物品",
							["tooltipTitle"] = "耐久度信息",
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Repair",
						["category"] = "General",
						["button"] = "TitanPanelRepairButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [15]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["builtIn"] = 1,
								["id"] = "Volume",
								["menuText"] = "音量控制",
								["savedVariables"] = {
									["OverrideBlizzSettings"] = false,
									["VolumeMaster"] = 1,
									["VolumeSFX"] = 0.5,
									["VolumeInboundChat"] = 1,
									["VolumeMusic"] = 0.5,
									["VolumeOutboundChat"] = 1,
									["VolumeAmbience"] = 0.5,
								},
								["version"] = "4.2.5.50000",
								["iconButtonWidth"] = 18,
								["iconWidth"] = 32,
								["tooltipTextFunction"] = "TitanPanelVolumeButton_GetTooltipText",
								["tooltipTitle"] = "音量信息",
							},
							["tooltipText"] = "主音量: 	|cffffffff70%|r\n音效音量: 	|cffffffff40%|r\n音乐音量: 	|cffffffff20%|r\n环境音量: 	|cffffffff30%|r\n麦克风音量: 	|cffffffff100%|r\n扬声器音量: 	|cffffffff100%|r\n|cff20ff20提示: 用鼠标左键来调节|r\n|cff20ff20音量.|r",
							["tooltipTitle"] = "音量信息",
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Volume",
						["category"] = "General",
						["button"] = "TitanPanelVolumeButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [16]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["builtIn"] = 1,
								["id"] = "XP",
								["menuText"] = "经验",
								["savedVariables"] = {
									["ShowSimpleNumOfKills"] = false,
									["ShowIcon"] = 1,
									["ShowSimpleRested"] = false,
									["ShowSimpleToLevel"] = false,
									["ShowLabelText"] = 1,
									["DisplayType"] = "ShowXPPerHourSession",
								},
								["version"] = "4.2.5.50000",
								["buttonTextFunction"] = "TitanPanelXPButton_GetButtonText",
								["iconWidth"] = 16,
								["tooltipTextFunction"] = "TitanPanelXPButton_GetTooltipText",
								["tooltipTitle"] = "经验相关信息",
							},
							["totalTime"] = 5765488.928010033,
							["initXP"] = 0,
							["startSessionTime"] = 1381054488,
							["accumXP"] = 0,
							["levelTime"] = 665609.9280100334,
							["tooltipText"] = "总共游戏时间: 	|cffffffff66天 17小时 30分 37秒|r\n当前等级的游戏时间: 	|cffffffff7天 16小时 52分 38秒|r\n本次连接游戏时间: 	|cffffffff1分 37秒|r\n\n当前级别总经验: 	|cffffffff93465000|r\n剩余: 	|cffffffff0|r\n当前等级所获经验: 	|cffffffff213326 (0.2%)|r\n升级所需经验: 	|cffffffff93251674 (99.8%)|r\n本次连接所获经验: 	|cffffffff0|r\n升级所需击杀数 (基于最后一个的经验 0): 	|cffffffff未知|r\n\n经验/小时 当前级别: 	|cffffffff1153|r\n经验/小时 本次连接: 	|cffffffff0|r\n升级时间 (按等级效率): 	|cffffffff3367天 7小时 49分 21秒|r\n升级时间 (按连接效率): 	|cffffffffN/A|r",
							["sessionXP"] = 0,
							["sessionTime"] = 1381054488,
							["tooltipTitle"] = "经验相关信息",
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "XP",
						["category"] = "General",
						["button"] = "TitanPanelXPButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [17]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["builtIn"] = 1,
								["id"] = "Mail",
								["menuText"] = "邮件",
								["savedVariables"] = {
									["HideMm"] = 1,
									["ShowColoredText"] = 1,
									["ShowIcon"] = 1,
									["ShowButtonText"] = 1,
									["ShowLabelText"] = 1,
								},
								["version"] = "4.2.5.50000",
								["buttonTextFunction"] = "TitanPanelMailButton_GetButtonText",
								["iconWidth"] = 16,
								["tooltipTextFunction"] = "TitanPanelMailButton_GetTooltipText",
								["icon"] = "Interface\\AddOns\\Titan\\TitanMail\\nomail",
								["tooltipTitle"] = "邮件资讯",
							},
							["tooltipText"] = "|cff20ff20你没有未读信件|r",
							["tooltipTitle"] = "邮件资讯",
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Mail",
						["category"] = "General",
						["button"] = "TitanPanelMailButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [18]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["builtIn"] = 1,
								["id"] = "Track",
								["menuText"] = "追踪",
								["savedVariables"] = {
									["CurrentTrackName"] = "无",
									["ShowColoredText"] = 1,
									["ShowIcon"] = 1,
									["DisplayOnRightSide"] = true,
								},
								["version"] = "4.2.5.50000",
								["iconWidth"] = 16,
								["tooltipTextFunction"] = "TitanPanelTrackButton_GetTooltipText",
								["icon"] = "Interface\\Minimap\\Tracking\\None",
								["tooltipTitle"] = "追踪资讯",
							},
							["tooltipText"] = "追踪类型:	|cffffffff无|r\n|cff20ff20提示:点击以选择追踪类型|r",
							["tooltipTitle"] = "追踪资讯",
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Track",
						["category"] = "General",
						["button"] = "TitanPanelTrackButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [19]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["builtIn"] = 1,
								["id"] = "WinterTimer",
								["menuText"] = "冬拥湖计时",
								["savedVariables"] = {
									["ShowColoredText"] = 1,
									["ShowIcon"] = 1,
									["DisplayOnRightSide"] = false,
								},
								["version"] = "4.2.5.50000",
								["buttonTextFunction"] = "TitanWinterTimerButton_GetButtonText",
								["iconWidth"] = 16,
								["tooltipTextFunction"] = "TitanWinterTimerButton_GetTooltipText",
								["icon"] = "Interface\\Icons\\Spell_Frost_WizardMark",
								["tooltipTitle"] = "冬拥湖计时器",
							},
							["tooltipText"] = "|cff20ff20显示距冬拥湖战斗开始的时间|r",
							["tooltipTitle"] = "冬拥湖计时器",
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "WinterTimer",
						["category"] = "General",
						["button"] = "TitanPanelWinterTimerButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [20]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["builtIn"] = 1,
								["id"] = "TolBarad",
								["menuText"] = "托尔巴拉德计时",
								["savedVariables"] = {
									["ShowColoredText"] = 1,
									["ShowIcon"] = 1,
									["DisplayOnRightSide"] = false,
								},
								["version"] = "4.2.5.50000",
								["buttonTextFunction"] = "TitanTolBaradButton_GetButtonText",
								["iconWidth"] = 16,
								["tooltipTextFunction"] = "TitanTolBaradButton_GetTooltipText",
								["icon"] = "Interface\\Icons\\Ability_DualWield",
								["tooltipTitle"] = "托尔巴拉德计时器",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "TolBarad",
						["category"] = "General",
						["button"] = "TitanPanelTolBaradButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [21]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "",
								["iconWidth"] = 16,
								["id"] = "TradeSkillInfo",
								["menuText"] = "TSI",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = false,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["version"] = "v2.2.4",
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "launcher",
								["icon"] = "Interface\\Icons\\INV_Elemental_Mote_Nether",
								["LDBVariables"] = {
									["type"] = "launcher",
									["name"] = "TradeSkillInfo",
									["suffix"] = "",
									["value"] = "",
									["text"] = "",
									["label"] = "TSI",
								},
							},
						},
						["notes"] = "",
						["plugin_type"] = "LDB: 'launcher'",
						["name"] = "TradeSkillInfo",
						["category"] = "General",
						["button"] = "TitanPanelTradeSkillInfoButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [22]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "",
								["iconWidth"] = 16,
								["id"] = "YssBossLoot",
								["menuText"] = "|cFF33FF99YssBossLoot|r",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = false,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["version"] = "",
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "launcher",
								["icon"] = "Interface\\Addons\\YssBossLoot\\Art\\skullwhite",
								["LDBVariables"] = {
									["type"] = "launcher",
									["name"] = "YssBossLoot",
									["suffix"] = "",
									["value"] = "",
									["text"] = "YssBossLoot",
									["label"] = "|cFF33FF99YssBossLoot|r",
								},
							},
						},
						["notes"] = "",
						["plugin_type"] = "LDB: 'launcher'",
						["name"] = "YssBossLoot",
						["category"] = "General",
						["button"] = "TitanPanelYssBossLootButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [23]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "",
								["iconWidth"] = 16,
								["id"] = "LFGForwarder",
								["menuText"] = "LFGForwarder",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = false,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["iconCoords"] = {
									0.025, -- [1]
									0.1, -- [2]
									0.05, -- [3]
									0.2, -- [4]
								},
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "launcher",
								["icon"] = "Interface\\LFGFrame\\LFG-Eye",
								["LDBVariables"] = {
									["type"] = "launcher",
									["name"] = "LFGForwarder",
									["suffix"] = "",
									["value"] = "",
									["text"] = "",
									["label"] = "",
								},
							},
						},
						["notes"] = "",
						["plugin_type"] = "LDB: 'launcher'",
						["name"] = "LFGForwarder",
						["category"] = "General",
						["button"] = "TitanPanelLFGForwarderButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [24]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!\nWill be registered as single LDB plugin after the normal registration.",
								["iconWidth"] = 16,
								["id"] = "AtlasLoot",
								["menuText"] = "AtlasLoot",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = false,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "launcher",
								["icon"] = "Interface\\Icons\\INV_Box_01",
								["LDBVariables"] = {
									["type"] = "launcher",
									["name"] = "AtlasLoot",
									["suffix"] = "",
									["value"] = "",
									["text"] = "",
									["label"] = "AtlasLoot",
								},
							},
						},
						["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!\nWill be registered as single LDB plugin after the normal registration.",
						["plugin_type"] = "LDB: 'launcher'",
						["name"] = "AtlasLoot",
						["category"] = "General",
						["button"] = "TitanPanelAtlasLootButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [25]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "\nWill be registered as single LDB plugin after the normal registration.",
								["iconWidth"] = 16,
								["id"] = "Omen",
								["menuText"] = "Omen",
								["category"] = "Combat",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = false,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["version"] = "3.1.2",
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "launcher",
								["icon"] = "Interface\\AddOns\\Omen\\icon",
								["LDBVariables"] = {
									["type"] = "launcher",
									["name"] = "Omen",
									["suffix"] = "",
									["value"] = "",
									["text"] = "",
									["label"] = "",
								},
							},
						},
						["notes"] = "\nWill be registered as single LDB plugin after the normal registration.",
						["plugin_type"] = "LDB: 'launcher'",
						["name"] = "Omen",
						["category"] = "Combat",
						["button"] = "TitanPanelOmenButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [26]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "\nWill be registered as single LDB plugin after the normal registration.",
								["iconWidth"] = 16,
								["id"] = "Skada",
								["menuText"] = "Skada",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = true,
									["DisplayOnRightSide"] = false,
									["ShowLabelText"] = true,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = true,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["version"] = "1.4-11",
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "data source",
								["icon"] = "Interface\\Icons\\Spell_Lightning_LightningBolt01",
								["LDBVariables"] = {
									["type"] = "data source",
									["name"] = "Skada",
									["suffix"] = "",
									["value"] = "",
									["text"] = "n/a",
									["label"] = "Skada",
								},
							},
						},
						["notes"] = "\nWill be registered as single LDB plugin after the normal registration.",
						["plugin_type"] = "LDB: 'data source'",
						["name"] = "Skada",
						["category"] = "General",
						["button"] = "TitanPanelSkadaButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [27]
				},
				["Extras"] = {
				},
			},
		},
	},
	["Player"] = "凛若@凯恩血蹄",
	["Version"] = "4.2.5.50000",
	["Profile"] = "凛若@凯恩血蹄",
}
TitanSkins = {
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\",
		["name"] = "Titan Default",
	}, -- [1]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Christmas Skin\\",
		["name"] = "Christmas",
	}, -- [2]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Charcoal Metal\\",
		["name"] = "Charcoal Metal",
	}, -- [3]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Crusader Skin\\",
		["name"] = "Crusader",
	}, -- [4]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Cursed Orange Skin\\",
		["name"] = "Cursed Orange",
	}, -- [5]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Dark Wood Skin\\",
		["name"] = "Dark Wood",
	}, -- [6]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Deep Cave Skin\\",
		["name"] = "Deep Cave",
	}, -- [7]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Elfwood Skin\\",
		["name"] = "Elfwood",
	}, -- [8]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Engineer Skin\\",
		["name"] = "Engineer",
	}, -- [9]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Frozen Metal Skin\\",
		["name"] = "Frozen Metal",
	}, -- [10]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Graphic Skin\\",
		["name"] = "Graphic",
	}, -- [11]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Graveyard Skin\\",
		["name"] = "Graveyard",
	}, -- [12]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Hidden Leaf Skin\\",
		["name"] = "Hidden Leaf",
	}, -- [13]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Holy Warrior Skin\\",
		["name"] = "Holy Warrior",
	}, -- [14]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Nightlife Skin\\",
		["name"] = "Nightlife",
	}, -- [15]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Orgrimmar Skin\\",
		["name"] = "Orgrimmar",
	}, -- [16]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Plate Skin\\",
		["name"] = "Plate",
	}, -- [17]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\Tribal Skin\\",
		["name"] = "Tribal",
	}, -- [18]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Titan\\Artwork\\Custom\\X-Perl\\",
		["name"] = "X-Perl",
	}, -- [19]
}
ServerTimeOffsets = {
}
ServerHourFormat = {
}
GoldArray = {
	["DISPLAYGPH"] = true,
	["VERSION2"] = true,
	["SORTBYNAME"] = true,
	["凛若_凯恩血蹄::Horde"] = 11389760410,
	["VIEWALL"] = true,
	["INITIALIZED"] = true,
}
